sudo: false
language: node_js
os: linux
node_js:
  - node
script:
  - npm run test:coveralls
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: GumH/EUaBkAi+Kdg+nS6nRqBSZ5oTWv0MGrxx6VNx0F5Ee8gBuCVQJ9vSSL8JRLDdhFcSYdzdctp4KDuIV5Ye7HJMhL4rc595DefZmS+EbvOr28LTYAuoP9K4kqR5SQqRFiiTjY1pfmlt4dRXCTABRFm2m1fC7/X8P8vPKZNVAyt414hsl6FT9WlGc/RaSuzrlyFMsptq4M5aUN4kEJJuWYuHKHRFF0dfZzcLKkNlxBNDjbCr+EaMX8zAhCQck6jC5pXfINZ45GLdI8rrk5RoBqufWvHsUv4XTvhQoHE8aDrK5q/rNIMZKFX1Xk3mOZ7YasE5rNSC7RYAHnNe/1r1fSbTF62pcmkzAssQHnW49+ItbFUyKKdQsgyH2z6gxjZ53dEp3AJMuiSgdyZyrtdmSfbe153NPRYzT2X7C3Al4feSbV+nCXTl2vZLYdAXlRZB4IMaHie8VXQ46zdrMx94yx29HezGj43B8wX0UC2tu6pccLb57rdWAaMYH4osvwPOAFj54iKugeCn5HxUDItJpcFP6AtCsq4tfQoJ3SYK0mKnfwANNbNfbzd59gmc9s5KroFa5vWmMs9Oat4Z7HAeimB6QLFQgubq6wDkwiBNUb26XRIykBgueTaco5vMo0IvTFf3e4vQeffMXLXKY0ZM+qzVvu01H7S4MbkO843r0M=
  app: salad-nu
