import {
  filterCoursesByStr,
  filterCoursesBySchoolSubject,
} from "../utils/searchUtils";

const courses = [
  {
    course_id: "020458",
    unique_id: "40967",
    school: "UC",
    title: "Introduction to Financial Accounting",
    subject: "ACCOUNT",
    number: "201-DL",
  },
  {
    course_id: "020459",
    unique_id: "40966",
    school: "UC",
    title: "Introduction to Managerial Accounting",
    subject: "ACCOUNT",
    number: "202-DL",
  },
  {
    course_id: "020460",
    unique_id: "41738",
    school: "UC",
    title: "Income Tax I",
    subject: "ACCOUNT",
    number: "208-DL",
  },
  {
    course_id: "020461",
    unique_id: "40965",
    school: "UC",
    title: "Intermediate Accounting I",
    subject: "ACCOUNT",
    number: "210-DL",
  },
  {
    course_id: "020467",
    unique_id: "41739",
    school: "UC",
    title: "Topics in Accounting:",
    subject: "ACCOUNT",
    number: "390-DL",
  },
  {
    course_id: "008702",
    unique_id: "41408",
    school: "WCAS",
    title: "Topics in African Studies",
    subject: "AFST",
    number: "390-0",
  },
  {
    course_id: "001195",
    unique_id: "41799",
    school: "WCAS",
    title: "Introduction to African-American Studies",
    subject: "AF_AM_ST",
    number: "236-0",
  },
  {
    course_id: "016191",
    unique_id: "41801",
    school: "WCAS",
    title: "Race, Class and Gender",
    subject: "AF_AM_ST",
    number: "250-0",
  },
  {
    course_id: "001218",
    unique_id: "41800",
    school: "WCAS",
    title: "Topics in African-American Studies",
    subject: "AF_AM_ST",
    number: "380-0",
  },
  {
    course_id: "001094",
    unique_id: "41678",
    school: "WCAS",
    title: "Culture & Society",
    subject: "ANTHRO",
    number: "211-0",
  },
  {
    course_id: "001095",
    unique_id: "41679",
    school: "WCAS",
    title: "Human Origins",
    subject: "ANTHRO",
    number: "213-0",
  },
  {
    course_id: "001096",
    unique_id: "41681",
    school: "WCAS",
    title: "Archaeology: Unearthing History",
    subject: "ANTHRO",
    number: "214-0",
  },
  {
    course_id: "001097",
    unique_id: "41747",
    school: "WCAS",
    title: "The Study of Culture through Language",
    subject: "ANTHRO",
    number: "215-0",
  },
  {
    course_id: "015103",
    unique_id: "41755",
    school: "WCAS",
    title: "Medical Anthropology",
    subject: "ANTHRO",
    number: "315-0",
  },
  {
    course_id: "001147",
    unique_id: "41682",
    school: "WCAS",
    title: "Topics In Anthropology",
    subject: "ANTHRO",
    number: "390-0",
  },
  {
    course_id: "002324",
    unique_id: "40258",
    school: "WCAS",
    title: "Arabic I",
    subject: "ARABIC",
    number: "111-1",
  },
  {
    course_id: "002325",
    unique_id: "40259",
    school: "WCAS",
    title: "Arabic I",
    subject: "ARABIC",
    number: "111-2",
  },
  {
    course_id: "002326",
    unique_id: "40260",
    school: "WCAS",
    title: "Arabic I",
    subject: "ARABIC",
    number: "111-3",
  },
  {
    course_id: "002327",
    unique_id: "41665",
    school: "WCAS",
    title: "Arabic II",
    subject: "ARABIC",
    number: "121-1",
  },
  {
    course_id: "002328",
    unique_id: "41666",
    school: "WCAS",
    title: "Arabic II",
    subject: "ARABIC",
    number: "121-2",
  },
  {
    course_id: "002329",
    unique_id: "41667",
    school: "WCAS",
    title: "Arabic II",
    subject: "ARABIC",
    number: "121-3",
  },
  {
    course_id: "001309",
    unique_id: "41442",
    school: "WCAS",
    title: "Introduction to Photography",
    subject: "ART",
    number: "250-0",
  },
  {
    course_id: "001335",
    unique_id: "40275",
    school: "WCAS",
    title: "Modern Cosmology",
    subject: "ASTRON",
    number: "101-0",
  },
  {
    course_id: "001339",
    unique_id: "40229",
    school: "WCAS",
    title: "Highlights of Astronomy",
    subject: "ASTRON",
    number: "120-0",
  },
  {
    course_id: "019819",
    unique_id: "42149",
    school: "WCAS",
    title: "Introduction to Biological Sciences at Northwestern",
    subject: "BIOL_SCI",
    number: "100-0",
  },
  {
    course_id: "021905",
    unique_id: "41130",
    school: "UC",
    title: "Concepts of Biology",
    subject: "BIOL_SCI",
    number: "170-DL",
  },
  {
    course_id: "019886",
    unique_id: "41687",
    school: "WCAS",
    title: "Physiology",
    subject: "BIOL_SCI",
    number: "217-0",
  },
  {
    course_id: "019885",
    unique_id: "41686",
    school: "WCAS",
    title: "Cell Biology",
    subject: "BIOL_SCI",
    number: "219-0",
  },
  {
    course_id: "019888",
    unique_id: "41688",
    school: "WCAS",
    title: "Genetics and Molecular Processes Laboratory",
    subject: "BIOL_SCI",
    number: "220-0",
  },
  {
    course_id: "019889",
    unique_id: "41689",
    school: "WCAS",
    title: "Cellular Processes Laboratory",
    subject: "BIOL_SCI",
    number: "221-0",
  },
  {
    course_id: "019890",
    unique_id: "41690",
    school: "WCAS",
    title: "Investigative Laboratory",
    subject: "BIOL_SCI",
    number: "222-0",
  },
  {
    course_id: "001389",
    unique_id: "41685",
    school: "WCAS",
    title: "Principles of Biochemistry",
    subject: "BIOL_SCI",
    number: "301-0",
  },
  {
    course_id: "021098",
    unique_id: "40968",
    school: "UC",
    title: "Human Anatomy",
    subject: "BIOL_SCI",
    number: "313-DL",
  },
  {
    course_id: "016362",
    unique_id: "41716",
    school: "UC",
    title: "Human Structure and Function",
    subject: "BIOL_SCI",
    number: "316-CN",
  },
  {
    course_id: "022047",
    unique_id: "41094",
    school: "UC",
    title: "Microbiology Lab",
    subject: "BIOL_SCI",
    number: "328-A",
  },
  {
    course_id: "018466",
    unique_id: "41093",
    school: "UC",
    title: "Microbiology",
    subject: "BIOL_SCI",
    number: "328-CN",
  },
  {
    course_id: "023615",
    unique_id: "41741",
    school: "UC",
    title: "Immunobiology",
    subject: "BIOL_SCI",
    number: "355-DL",
  },
  {
    course_id: "015579",
    unique_id: "41888",
    school: "LAW",
    title: "Business Associations",
    subject: "BUSCOM",
    number: "601S",
  },
  {
    course_id: "007031",
    unique_id: "41908",
    school: "LAW",
    title: "Securities Regulation",
    subject: "BUSCOM",
    number: "620",
  },
  {
    course_id: "006942",
    unique_id: "41896",
    school: "LAW",
    title: "Entrepreneurship Law",
    subject: "BUSCOM",
    number: "631",
  },
  {
    course_id: "016014",
    unique_id: "41899",
    school: "LAW",
    title: "Structuring Transactions:  Real Estate",
    subject: "BUSCOM",
    number: "633I",
  },
  {
    course_id: "007000",
    unique_id: "41897",
    school: "LAW",
    title: "Mergers and Acquisitions",
    subject: "BUSCOM",
    number: "638",
  },
  {
    course_id: "006915",
    unique_id: "41887",
    school: "LAW",
    title: "Commercial Law:  Secured Transactions",
    subject: "BUSCOM",
    number: "660",
  },
  {
    course_id: "015327",
    unique_id: "41860",
    school: "LAW",
    title: "Corporate Restructuring:  Bankruptcy Reorganizations",
    subject: "BUSCOM",
    number: "667",
  },
  {
    course_id: "010968",
    unique_id: "41902",
    school: "LAW",
    title: "Practicum: Corporate Counsel",
    subject: "BUSCOM",
    number: "670PS",
  },
  {
    course_id: "020843",
    unique_id: "41892",
    school: "LAW",
    title: "Contracts (LLM)",
    subject: "BUSCOM",
    number: "701C",
  },
  {
    course_id: "021390",
    unique_id: "41919",
    school: "LAW",
    title: "Employment Law",
    subject: "BUSCOM",
    number: "925-0",
  },
  {
    course_id: "021384",
    unique_id: "41975",
    school: "UC",
    title: "Modeling Methods",
    subject: "BUS_ANLY",
    number: "202-DL",
  },
  {
    course_id: "021380",
    unique_id: "40976",
    school: "UC",
    title: "Analytics Communication & Management",
    subject: "BUS_ANLY",
    number: "204-DL",
  },
  {
    course_id: "018633",
    unique_id: "40657",
    school: "WCAS",
    title: "Analysis of Field Experience",
    subject: "CFS",
    number: "291-0",
  },
  {
    course_id: "021511",
    unique_id: "40658",
    school: "WCAS",
    title: "Field Studies in Business Culture",
    subject: "CFS",
    number: "388-0",
  },
  {
    course_id: "020519",
    unique_id: "40649",
    school: "WCAS",
    title: "Field Studies in Public Health",
    subject: "CFS",
    number: "392-0",
  },
  {
    course_id: "017400",
    unique_id: "41995",
    school: "WCAS",
    title: "Modern Workplace Culture",
    subject: "CFS",
    number: "393-1",
  },
  {
    course_id: "017401",
    unique_id: "41996",
    school: "WCAS",
    title: "Contemporary Issues in the Workplace",
    subject: "CFS",
    number: "393-2",
  },
  {
    course_id: "017402",
    unique_id: "40663",
    school: "WCAS",
    title: "Legal Culture & Process",
    subject: "CFS",
    number: "394-1",
  },
  {
    course_id: "017403",
    unique_id: "40664",
    school: "WCAS",
    title: "Contemporary Issues in Law",
    subject: "CFS",
    number: "394-2",
  },
  {
    course_id: "017782",
    unique_id: "40666",
    school: "WCAS",
    title: "Business Workplace Culture",
    subject: "CFS",
    number: "395-1",
  },
  {
    course_id: "017783",
    unique_id: "40670",
    school: "WCAS",
    title: "Contemporary Issues: Business Field Studies",
    subject: "CFS",
    number: "395-2",
  },
  {
    course_id: "018515",
    unique_id: "40672",
    school: "WCAS",
    title: "Field Studies in Civic Engagement",
    subject: "CFS",
    number: "397-0",
  },
  {
    course_id: "020001",
    unique_id: "40671",
    school: "WCAS",
    title: "Field Studies in Humanities",
    subject: "CFS",
    number: "398-0",
  },
  {
    course_id: "019546",
    unique_id: "40647",
    school: "WCAS",
    title: "Civic Engagement and Graduate Education",
    subject: "CFS",
    number: "495-0",
  },
  {
    course_id: "019818",
    unique_id: "40066",
    school: "WCAS",
    title: "Introduction to Calculus and Chemistry",
    subject: "CHEM",
    number: "100-0",
  },
  {
    course_id: "019951",
    unique_id: "41964",
    school: "WCAS",
    title: "Introduction to Problem Solving in Chemistry",
    subject: "CHEM",
    number: "100-BR",
  },
  {
    course_id: "022460",
    unique_id: "41881",
    school: "WCAS",
    title: "Quantitative Problem Solving in Chemistry",
    subject: "CHEM",
    number: "110-0",
  },
  {
    course_id: "022461",
    unique_id: "41882",
    school: "WCAS",
    title: "General Chemistry 1",
    subject: "CHEM",
    number: "131-0",
  },
  {
    course_id: "022462",
    unique_id: "41883",
    school: "WCAS",
    title: "General Chemistry 2",
    subject: "CHEM",
    number: "132-0",
  },
  {
    course_id: "022463",
    unique_id: "41765",
    school: "WCAS",
    title: "General Chemistry Laboratory 1",
    subject: "CHEM",
    number: "141-0",
  },
  {
    course_id: "022464",
    unique_id: "40076",
    school: "WCAS",
    title: "General Chemistry Laboratory 2",
    subject: "CHEM",
    number: "142-0",
  },
  {
    course_id: "021735",
    unique_id: "40054",
    school: "WCAS",
    title: "Foundations of Organic Chemstry",
    subject: "CHEM",
    number: "199-BR",
  },
  {
    course_id: "001467",
    unique_id: "41884",
    school: "WCAS",
    title: "Organic Chemistry",
    subject: "CHEM",
    number: "210-1",
  },
  {
    course_id: "001468",
    unique_id: "41885",
    school: "WCAS",
    title: "Organic Chemistry",
    subject: "CHEM",
    number: "210-2",
  },
  {
    course_id: "001469",
    unique_id: "41886",
    school: "WCAS",
    title: "Organic Chemistry",
    subject: "CHEM",
    number: "210-3",
  },
  {
    course_id: "020687",
    unique_id: "40073",
    school: "WCAS",
    title: "Organic Chemistry Lab I",
    subject: "CHEM",
    number: "230-2",
  },
  {
    course_id: "020688",
    unique_id: "40075",
    school: "WCAS",
    title: "Organic Chemistry Lab II",
    subject: "CHEM",
    number: "230-3",
  },
  {
    course_id: "002331",
    unique_id: "41472",
    school: "WCAS",
    title: "Chinese I",
    subject: "CHINESE",
    number: "111-1",
  },
  {
    course_id: "002332",
    unique_id: "41473",
    school: "WCAS",
    title: "Chinese I",
    subject: "CHINESE",
    number: "111-2",
  },
  {
    course_id: "002333",
    unique_id: "41474",
    school: "WCAS",
    title: "Chinese I",
    subject: "CHINESE",
    number: "111-3",
  },
  {
    course_id: "002334",
    unique_id: "41475",
    school: "WCAS",
    title: "Chinese II",
    subject: "CHINESE",
    number: "121-1",
  },
  {
    course_id: "002335",
    unique_id: "41476",
    school: "WCAS",
    title: "Chinese II",
    subject: "CHINESE",
    number: "121-2",
  },
  {
    course_id: "002336",
    unique_id: "41477",
    school: "WCAS",
    title: "Chinese II",
    subject: "CHINESE",
    number: "121-3",
  },
  {
    course_id: "016549",
    unique_id: "40974",
    school: "UC",
    title: "Introduction to Object-Oriented Programming",
    subject: "CIS",
    number: "212-CN",
  },
  {
    course_id: "024019",
    unique_id: "41853",
    school: "UC",
    title: "Data Engineering",
    subject: "CIS",
    number: "326-DL",
  },
  {
    course_id: "017771",
    unique_id: "41076",
    school: "UC",
    title: "Telecommunications Networks",
    subject: "CIS",
    number: "413-DL",
  },
  {
    course_id: "017526",
    unique_id: "41074",
    school: "UC",
    title: "Database Systems Design & Implementation",
    subject: "CIS",
    number: "417-DL",
  },
  {
    course_id: "021007",
    unique_id: "41073",
    school: "UC",
    title: "Big Data Management and Analytics",
    subject: "CIS",
    number: "436-DL",
  },
  {
    course_id: "022842",
    unique_id: "41949",
    school: "UC",
    title: "Enterprise Security Strategy",
    subject: "CIS",
    number: "453-DL",
  },
  {
    course_id: "019168",
    unique_id: "42080",
    school: "UC",
    title: "Project Management Concepts",
    subject: "CIS",
    number: "494-DL",
  },
  {
    course_id: "021575",
    unique_id: "42030",
    school: "UC",
    title: "Information Technology Business Writing and Communication",
    subject: "CIS",
    number: "496-DL",
  },
  {
    course_id: "022512",
    unique_id: "40963",
    school: "MEAS",
    title: "M.S. Research Paper for non-thesis option",
    subject: "CIV_ENV",
    number: "508-0",
  },
  {
    course_id: "023377",
    unique_id: "41072",
    school: "UC",
    title: "Clinical Research Design & Methodology",
    subject: "CLIN_RES",
    number: "403-DL",
  },
  {
    course_id: "004368",
    unique_id: "42211",
    school: "SPCH",
    title: "Internship",
    subject: "CMN",
    number: "340-0",
  },
  {
    course_id: "023439",
    unique_id: "41983",
    school: "UC",
    title: "High School Coding Camp",
    subject: "CODING",
    number: "100-DL",
  },
  {
    course_id: "022302",
    unique_id: "40992",
    school: "UC",
    title: "Coding Boot Camp",
    subject: "CODING",
    number: "200-0",
  },
  {
    course_id: "022238",
    unique_id: "40991",
    school: "UC",
    title: "Coding Boot Camp",
    subject: "CODING",
    number: "200-0",
  },
  {
    course_id: "004134",
    unique_id: "41450",
    school: "SPCH",
    title: "Public Speaking",
    subject: "COMM_ST",
    number: "102-0",
  },
  {
    course_id: "004192",
    unique_id: "40673",
    school: "SPCH",
    title: "Theories of Persuasion",
    subject: "COMM_ST",
    number: "205-0",
  },
  {
    course_id: "021922",
    unique_id: "40736",
    school: "SPCH",
    title: "Intro to Health Communication",
    subject: "COMM_ST",
    number: "246-0",
  },
  {
    course_id: "004206",
    unique_id: "41451",
    school: "SPCH",
    title: "Team Leadership and Decision Making",
    subject: "COMM_ST",
    number: "250-0",
  },
  {
    course_id: "023430",
    unique_id: "41092",
    school: "UC",
    title: "Team Leadership and Decision Making",
    subject: "COMM_ST",
    number: "250-DL",
  },
  {
    course_id: "004242",
    unique_id: "41452",
    school: "SPCH",
    title: "Solving Problems in Applied Organizational Communication",
    subject: "COMM_ST",
    number: "365-0",
  },
  {
    course_id: "001605",
    unique_id: "41405",
    school: "WCAS",
    title: "Interpreting Culture",
    subject: "COMP_LIT",
    number: "202-0",
  },
  {
    course_id: "023045",
    unique_id: "41407",
    school: "WCAS",
    title: "Literatures in Translation",
    subject: "COMP_LIT",
    number: "270-0",
  },
  {
    course_id: "018661",
    unique_id: "41406",
    school: "WCAS",
    title: "Studies in World Literature",
    subject: "COMP_LIT",
    number: "301-0",
  },
  {
    course_id: "004969",
    unique_id: "41951",
    school: "MEAS",
    title: "Data Structures & Algorithms",
    subject: "COMP_SCI",
    number: "214-0",
  },
  {
    course_id: "022525",
    unique_id: "41952",
    school: "MEAS",
    title: "Introduction to Computational Photography",
    subject: "COMP_SCI",
    number: "331-0",
  },
  {
    course_id: "008177",
    unique_id: "40278",
    school: "MEAS",
    title: "Machine Learning",
    subject: "COMP_SCI",
    number: "349-0",
  },
  {
    course_id: "022536",
    unique_id: "41674",
    school: "MEAS",
    title: "Special Topics in Computer Science",
    subject: "COMP_SCI",
    number: "396-0",
  },
  {
    course_id: "006982",
    unique_id: "41903",
    school: "LAW",
    title: "Practicum:  Judicial",
    subject: "CONPUB",
    number: "647",
  },
  {
    course_id: "020757",
    unique_id: "41904",
    school: "LAW",
    title: "Practicum:  Judicial",
    subject: "CONPUB",
    number: "647D",
  },
  {
    course_id: "022037",
    unique_id: "41898",
    school: "LAW",
    title:
      "Policing Chicago?s Communities:Examining historical & current practices & analyzing for reform",
    subject: "CONPUB",
    number: "740",
  },
  {
    course_id: "017947",
    unique_id: "40791",
    school: "MEAS",
    title: "Cooperative Engineering Education",
    subject: "CRDV",
    number: "310-1",
  },
  {
    course_id: "022139",
    unique_id: "40827",
    school: "MEAS",
    title: "International Cooperative Engineering Education",
    subject: "CRDV",
    number: "310-1-GM",
  },
  {
    course_id: "017948",
    unique_id: "40792",
    school: "MEAS",
    title: "Cooperative Engineering Education",
    subject: "CRDV",
    number: "310-2",
  },
  {
    course_id: "022140",
    unique_id: "40828",
    school: "MEAS",
    title: "International Cooperative Engineering Education",
    subject: "CRDV",
    number: "310-2-GM",
  },
  {
    course_id: "017949",
    unique_id: "40793",
    school: "MEAS",
    title: "Cooperative Engineering Education",
    subject: "CRDV",
    number: "310-3",
  },
  {
    course_id: "022141",
    unique_id: "40829",
    school: "MEAS",
    title: "International Cooperative Engineering Education",
    subject: "CRDV",
    number: "310-3-GM",
  },
  {
    course_id: "017950",
    unique_id: "40794",
    school: "MEAS",
    title: "Cooperative Engineering Education",
    subject: "CRDV",
    number: "310-4",
  },
  {
    course_id: "022174",
    unique_id: "40859",
    school: "MEAS",
    title: "International Cooperative Engineering Education",
    subject: "CRDV",
    number: "310-4-GM",
  },
  {
    course_id: "017951",
    unique_id: "40795",
    school: "MEAS",
    title: "Cooperative Engineering Education",
    subject: "CRDV",
    number: "310-5",
  },
  {
    course_id: "022175",
    unique_id: "40860",
    school: "MEAS",
    title: "International Cooperative Engineering Education",
    subject: "CRDV",
    number: "310-5-GM",
  },
  {
    course_id: "017952",
    unique_id: "40796",
    school: "MEAS",
    title: "Cooperative Engineering Education",
    subject: "CRDV",
    number: "310-6",
  },
  {
    course_id: "022176",
    unique_id: "40861",
    school: "MEAS",
    title: "International Cooperative Engineering Education",
    subject: "CRDV",
    number: "310-6-GM",
  },
  {
    course_id: "020079",
    unique_id: "40822",
    school: "MEAS",
    title: "Cooperative Engineering Education: Half-time",
    subject: "CRDV",
    number: "310-7",
  },
  {
    course_id: "022142",
    unique_id: "40830",
    school: "MEAS",
    title: "International Cooperative Engineering Education: Half-Time",
    subject: "CRDV",
    number: "310-7-GM",
  },
  {
    course_id: "017953",
    unique_id: "40797",
    school: "MEAS",
    title: "Professional Engineering Internship",
    subject: "CRDV",
    number: "311-1",
  },
  {
    course_id: "022143",
    unique_id: "40831",
    school: "MEAS",
    title: "International Engineering Internship",
    subject: "CRDV",
    number: "311-1-GM",
  },
  {
    course_id: "017954",
    unique_id: "40798",
    school: "MEAS",
    title: "Professional Engineering Internship",
    subject: "CRDV",
    number: "311-2",
  },
  {
    course_id: "022144",
    unique_id: "40832",
    school: "MEAS",
    title: "International Engineering Internship",
    subject: "CRDV",
    number: "311-2-GM",
  },
  {
    course_id: "017955",
    unique_id: "40799",
    school: "MEAS",
    title: "Professional Engineering Internship",
    subject: "CRDV",
    number: "311-3",
  },
  {
    course_id: "022145",
    unique_id: "40833",
    school: "MEAS",
    title: "International Engineering Internship",
    subject: "CRDV",
    number: "311-3-GM",
  },
  {
    course_id: "020081",
    unique_id: "40824",
    school: "MEAS",
    title: "Engineering Internship: Half-time",
    subject: "CRDV",
    number: "311-7",
  },
  {
    course_id: "022147",
    unique_id: "40834",
    school: "MEAS",
    title: "International Engineering Internship: Half-Time",
    subject: "CRDV",
    number: "311-7-GM",
  },
  {
    course_id: "019009",
    unique_id: "40807",
    school: "MEAS",
    title: "Undergraduate Engineering Projects in Service Learning",
    subject: "CRDV",
    number: "312-1",
  },
  {
    course_id: "022150",
    unique_id: "40835",
    school: "MEAS",
    title: "International Engineering Service Learning",
    subject: "CRDV",
    number: "312-1-GM",
  },
  {
    course_id: "019010",
    unique_id: "40808",
    school: "MEAS",
    title: "Undergraduate Engineering Projects in Service Learning",
    subject: "CRDV",
    number: "312-2",
  },
  {
    course_id: "022151",
    unique_id: "40836",
    school: "MEAS",
    title: "International Engineering Service Learning",
    subject: "CRDV",
    number: "312-2-GM",
  },
  {
    course_id: "019011",
    unique_id: "40809",
    school: "MEAS",
    title: "Undergraduate Engineering Projects in Service Learning",
    subject: "CRDV",
    number: "312-3",
  },
  {
    course_id: "022152",
    unique_id: "40837",
    school: "MEAS",
    title: "International Engineering Service Learning",
    subject: "CRDV",
    number: "312-3-GM",
  },
  {
    course_id: "020082",
    unique_id: "40825",
    school: "MEAS",
    title: "Engineering Projects in Service Learning: Half-time",
    subject: "CRDV",
    number: "312-7",
  },
  {
    course_id: "022153",
    unique_id: "40838",
    school: "MEAS",
    title: "International Engineering Service Learning: Half-Time",
    subject: "CRDV",
    number: "312-7-GM",
  },
  {
    course_id: "019196",
    unique_id: "40813",
    school: "MEAS",
    title: "Undergraduate Engineering Research",
    subject: "CRDV",
    number: "313-1",
  },
  {
    course_id: "022154",
    unique_id: "40839",
    school: "MEAS",
    title: "International Engineering Research Experience",
    subject: "CRDV",
    number: "313-1-GM",
  },
  {
    course_id: "019197",
    unique_id: "40814",
    school: "MEAS",
    title: "Undergraduate Engineering Research",
    subject: "CRDV",
    number: "313-2",
  },
  {
    course_id: "022155",
    unique_id: "40840",
    school: "MEAS",
    title: "International Engineering Research Experience",
    subject: "CRDV",
    number: "313-2-GM",
  },
  {
    course_id: "019198",
    unique_id: "40815",
    school: "MEAS",
    title: "Undergraduate Engineering Research",
    subject: "CRDV",
    number: "313-3",
  },
  {
    course_id: "022156",
    unique_id: "40841",
    school: "MEAS",
    title: "International Engineering Research Experience",
    subject: "CRDV",
    number: "313-3-GM",
  },
  {
    course_id: "020080",
    unique_id: "40823",
    school: "MEAS",
    title: "Engineering Research Experience: Half-time",
    subject: "CRDV",
    number: "313-7",
  },
  {
    course_id: "022157",
    unique_id: "40842",
    school: "MEAS",
    title: "International Engineering Research Experience: Half-Time",
    subject: "CRDV",
    number: "313-7-GM",
  },
  {
    course_id: "017956",
    unique_id: "40800",
    school: "MEAS",
    title: "Cooperative Engineering Education",
    subject: "CRDV",
    number: "410-1",
  },
  {
    course_id: "022158",
    unique_id: "40843",
    school: "MEAS",
    title: "International Cooperative Engineering Education",
    subject: "CRDV",
    number: "410-1-GM",
  },
  {
    course_id: "017957",
    unique_id: "40801",
    school: "MEAS",
    title: "Cooperative Engineering Education",
    subject: "CRDV",
    number: "410-2",
  },
  {
    course_id: "022159",
    unique_id: "40844",
    school: "MEAS",
    title: "International Cooperative Engineering Education",
    subject: "CRDV",
    number: "410-2-GM",
  },
  {
    course_id: "017958",
    unique_id: "40802",
    school: "MEAS",
    title: "Cooperative Engineering Education",
    subject: "CRDV",
    number: "410-3",
  },
  {
    course_id: "022160",
    unique_id: "40845",
    school: "MEAS",
    title: "International Cooperative Engineering Education",
    subject: "CRDV",
    number: "410-3-GM",
  },
  {
    course_id: "017959",
    unique_id: "40803",
    school: "MEAS",
    title: "Cooperative Engineering Education",
    subject: "CRDV",
    number: "410-4",
  },
  {
    course_id: "022177",
    unique_id: "40862",
    school: "MEAS",
    title: "International Cooperative Engineering Education",
    subject: "CRDV",
    number: "410-4-GM",
  },
  {
    course_id: "020076",
    unique_id: "40819",
    school: "MEAS",
    title: "Cooperative Engineering Education: Half-time",
    subject: "CRDV",
    number: "410-7",
  },
  {
    course_id: "022161",
    unique_id: "40846",
    school: "MEAS",
    title: "International Cooperative Engineering Education: Half-Time",
    subject: "CRDV",
    number: "410-7-GM",
  },
  {
    course_id: "017960",
    unique_id: "40804",
    school: "MEAS",
    title: "Professional Engineering Internship",
    subject: "CRDV",
    number: "411-1",
  },
  {
    course_id: "022162",
    unique_id: "40847",
    school: "MEAS",
    title: "International Engineering Internship",
    subject: "CRDV",
    number: "411-1-GM",
  },
  {
    course_id: "017961",
    unique_id: "40805",
    school: "MEAS",
    title: "Professional Engineering Internship",
    subject: "CRDV",
    number: "411-2",
  },
  {
    course_id: "022163",
    unique_id: "40848",
    school: "MEAS",
    title: "International Engineering Internship",
    subject: "CRDV",
    number: "411-2-GM",
  },
  {
    course_id: "017962",
    unique_id: "40806",
    school: "MEAS",
    title: "Professional Engineering Internship",
    subject: "CRDV",
    number: "411-3",
  },
  {
    course_id: "022164",
    unique_id: "40849",
    school: "MEAS",
    title: "International Engineering Internship",
    subject: "CRDV",
    number: "411-3-GM",
  },
  {
    course_id: "020077",
    unique_id: "40820",
    school: "MEAS",
    title: "Engineering Internship: Half-time",
    subject: "CRDV",
    number: "411-7",
  },
  {
    course_id: "022165",
    unique_id: "40850",
    school: "MEAS",
    title: "International Engineering Internship: Half-Time",
    subject: "CRDV",
    number: "411-7-GM",
  },
  {
    course_id: "019012",
    unique_id: "40810",
    school: "MEAS",
    title: "Graduate Engineering Projects in Service Learning",
    subject: "CRDV",
    number: "412-1",
  },
  {
    course_id: "022166",
    unique_id: "40851",
    school: "MEAS",
    title: "International Engineering Service Learning",
    subject: "CRDV",
    number: "412-1-GM",
  },
  {
    course_id: "019013",
    unique_id: "40811",
    school: "MEAS",
    title: "Graduate Engineering Projects in Service Learning",
    subject: "CRDV",
    number: "412-2",
  },
  {
    course_id: "022167",
    unique_id: "40852",
    school: "MEAS",
    title: "International Engineering Service Learning",
    subject: "CRDV",
    number: "412-2-GM",
  },
  {
    course_id: "019014",
    unique_id: "40812",
    school: "MEAS",
    title: "Graduate Engineering Projects in Service Learning",
    subject: "CRDV",
    number: "412-3",
  },
  {
    course_id: "022168",
    unique_id: "40853",
    school: "MEAS",
    title: "International Engineering Service Learning",
    subject: "CRDV",
    number: "412-3-GM",
  },
  {
    course_id: "020083",
    unique_id: "40826",
    school: "MEAS",
    title: "Engineering Projects in Service Learning: Half-time",
    subject: "CRDV",
    number: "412-7",
  },
  {
    course_id: "022169",
    unique_id: "40854",
    school: "MEAS",
    title: "International Engineering Service Learning: Half-Time",
    subject: "CRDV",
    number: "412-7-GM",
  },
  {
    course_id: "019816",
    unique_id: "40818",
    school: "MEAS",
    title: "Engineering Research",
    subject: "CRDV",
    number: "413-1",
  },
  {
    course_id: "022170",
    unique_id: "40855",
    school: "MEAS",
    title: "International Engineering Research Experience",
    subject: "CRDV",
    number: "413-1-GM",
  },
  {
    course_id: "019814",
    unique_id: "40816",
    school: "MEAS",
    title: "Engineering Research",
    subject: "CRDV",
    number: "413-2",
  },
  {
    course_id: "022171",
    unique_id: "40856",
    school: "MEAS",
    title: "International Engineering Research Experience",
    subject: "CRDV",
    number: "413-2-GM",
  },
  {
    course_id: "019815",
    unique_id: "40817",
    school: "MEAS",
    title: "Engineering Research",
    subject: "CRDV",
    number: "413-3",
  },
  {
    course_id: "022172",
    unique_id: "40857",
    school: "MEAS",
    title: "International Engineering Research Experience",
    subject: "CRDV",
    number: "413-3-GM",
  },
  {
    course_id: "020078",
    unique_id: "40821",
    school: "MEAS",
    title: "Engineering Research Experience: Half-time",
    subject: "CRDV",
    number: "413-7",
  },
  {
    course_id: "022173",
    unique_id: "40858",
    school: "MEAS",
    title: "International Engineering Research Experience: Half-Time",
    subject: "CRDV",
    number: "413-7-GM",
  },
  {
    course_id: "023292",
    unique_id: "40863",
    school: "MEAS",
    title: "Career Development for Student Entrepreneurs",
    subject: "CRDV",
    number: "414-1",
  },
  {
    course_id: "023293",
    unique_id: "40864",
    school: "MEAS",
    title: "Career Development for Student Entrepreneurs",
    subject: "CRDV",
    number: "414-2",
  },
  {
    course_id: "023294",
    unique_id: "40865",
    school: "MEAS",
    title: "Career Development for Student Entrepreneurs",
    subject: "CRDV",
    number: "414-3",
  },
  {
    course_id: "023295",
    unique_id: "40866",
    school: "MEAS",
    title: "Career Development for Student Entrepreneurs",
    subject: "CRDV",
    number: "414-4",
  },
  {
    course_id: "023296",
    unique_id: "40867",
    school: "MEAS",
    title: "Career Development for Student Entrepreneurs",
    subject: "CRDV",
    number: "414-5",
  },
  {
    course_id: "023297",
    unique_id: "40868",
    school: "MEAS",
    title: "Career Development for Student Entrepreneurs",
    subject: "CRDV",
    number: "414-6",
  },
  {
    course_id: "023298",
    unique_id: "40869",
    school: "MEAS",
    title: "Career Development for Student Entrepreneurs",
    subject: "CRDV",
    number: "414-7",
  },
  {
    course_id: "005455",
    unique_id: "40790",
    school: "MEAS",
    title: "Crown Family Graduate Internship",
    subject: "CRDV",
    number: "510-0",
  },
  {
    course_id: "024054",
    unique_id: "41900",
    school: "LAW",
    title: "Criminal Law, Race, and Blame",
    subject: "CRIM",
    number: "694",
  },
  {
    course_id: "020808",
    unique_id: "41099",
    school: "UC",
    title: "Anatomy and Physiology of the Vocal Mechanism",
    subject: "CSD",
    number: "301-DL",
  },
  {
    course_id: "020810",
    unique_id: "41098",
    school: "UC",
    title: "Phonetics",
    subject: "CSD",
    number: "305-DL",
  },
  {
    course_id: "020966",
    unique_id: "41097",
    school: "UC",
    title: "Introduction to Audiology",
    subject: "CSD",
    number: "318-DL",
  },
  {
    course_id: "022930",
    unique_id: "41095",
    school: "UC",
    title: "Aural Rehabilitation",
    subject: "CSD",
    number: "319-DL",
  },
  {
    course_id: "020967",
    unique_id: "41096",
    school: "UC",
    title: "Language Development Usage",
    subject: "CSD",
    number: "392-DL",
  },
  {
    course_id: "020248",
    unique_id: "41614",
    school: "SPCH",
    title: "Research Practicum in Communication Sciences and Disorders",
    subject: "CSD",
    number: "398-0",
  },
  {
    course_id: "022882",
    unique_id: "40144",
    school: "SPCH",
    title: "Foundations of Clinical and Professional Practice",
    subject: "CSD",
    number: "409-4",
  },
  {
    course_id: "022886",
    unique_id: "40145",
    school: "SPCH",
    title: "Foundations of Clinical and Professional Practice",
    subject: "CSD",
    number: "409-8",
  },
  {
    course_id: "011480",
    unique_id: "40126",
    school: "SPCH",
    title: "Clinical Practicum in Audiology",
    subject: "CSD",
    number: "415-4",
  },
  {
    course_id: "022888",
    unique_id: "40146",
    school: "SPCH",
    title: "Clinical Practicum in Audiology",
    subject: "CSD",
    number: "415-8",
  },
  {
    course_id: "004451",
    unique_id: "40122",
    school: "SPCH",
    title: "Pediatric Audiology",
    subject: "CSD",
    number: "419-0",
  },
  {
    course_id: "021070",
    unique_id: "40138",
    school: "SPCH",
    title: "Fundamentals of Vestibular Science",
    subject: "CSD",
    number: "428-0",
  },
  {
    course_id: "004477",
    unique_id: "40124",
    school: "SPCH",
    title: "Augmentative and Alternative Communication Across the Lifespan",
    subject: "CSD",
    number: "461-0",
  },
  {
    course_id: "021716",
    unique_id: "40139",
    school: "SPCH",
    title: "Professional Issues in Speech Language Pathology",
    subject: "CSD",
    number: "462-0",
  },
  {
    course_id: "021719",
    unique_id: "40141",
    school: "SPCH",
    title: "Advanced Clinical Methods 1",
    subject: "CSD",
    number: "475-0",
  },
  {
    course_id: "021718",
    unique_id: "40140",
    school: "SPCH",
    title: "Advanced Clinical Methods 2",
    subject: "CSD",
    number: "477-0",
  },
  {
    course_id: "004559",
    unique_id: "40125",
    school: "SPCH",
    title: "Externship: Clinical Practicum",
    subject: "CSD",
    number: "479-0",
  },
  {
    course_id: "022876",
    unique_id: "40143",
    school: "SPCH",
    title: "Pediatric Amplification and Educational Audiology",
    subject: "CSD",
    number: "519-0",
  },
  {
    course_id: "004464",
    unique_id: "40123",
    school: "SPCH",
    title: "Hearing Loss Prevention and Conservation",
    subject: "CSD",
    number: "522-0",
  },
  {
    course_id: "023687",
    unique_id: "40151",
    school: "SPCH",
    title: "Advanced Scientific Clinical Decision Making I",
    subject: "CSD",
    number: "558-6",
  },
  {
    course_id: "022371",
    unique_id: "41589",
    school: "SPCH",
    title: "Leadership for Speech-Language Pathologists",
    subject: "CSD",
    number: "563-6",
  },
  {
    course_id: "022374",
    unique_id: "40142",
    school: "SPCH",
    title: "Digital Literacies for the Speech Language Pathologist",
    subject: "CSD",
    number: "566-6",
  },
  {
    course_id: "015981",
    unique_id: "40135",
    school: "SPCH",
    title: "Seminar: Capstone Project",
    subject: "CSD",
    number: "570-3",
  },
  {
    course_id: "023690",
    unique_id: "40148",
    school: "SPCH",
    title: "Professional Integration and Reflective Practice II",
    subject: "CSD",
    number: "573-6B",
  },
  {
    course_id: "023688",
    unique_id: "40147",
    school: "SPCH",
    title: "Culminating Project Design",
    subject: "CSD",
    number: "574-6",
  },
  {
    course_id: "015985",
    unique_id: "40136",
    school: "SPCH",
    title: "Clinical Externship",
    subject: "CSD",
    number: "580-4",
  },
  {
    course_id: "023331",
    unique_id: "40994",
    school: "UC",
    title: "Cybersecurity Boot Camp",
    subject: "CYBER_BC",
    number: "200-0",
  },
  {
    course_id: "022762",
    unique_id: "40998",
    school: "UC",
    title: "Data Science and Visualization Boot Camp",
    subject: "DATA_BC",
    number: "200-0",
  },
  {
    course_id: "022761",
    unique_id: "40997",
    school: "UC",
    title: "Data Science and Visualization Boot Camp",
    subject: "DATA_BC",
    number: "200-0",
  },
  {
    course_id: "017630",
    unique_id: "40977",
    school: "UC",
    title: "Divorce Mediation",
    subject: "DIV_MED",
    number: "201-0",
  },
  {
    course_id: "022298",
    unique_id: "41861",
    school: "MEAS",
    title: "Innovation in Context",
    subject: "DSGN",
    number: "460-0",
  },
  {
    course_id: "021746",
    unique_id: "40052",
    school: "WCAS",
    title: "Introduction to Problem-Solving in Economics",
    subject: "ECON",
    number: "100-BR",
  },
  {
    course_id: "001646",
    unique_id: "40055",
    school: "WCAS",
    title: "Introduction to Macroeconomics",
    subject: "ECON",
    number: "201-0",
  },
  {
    course_id: "001647",
    unique_id: "41867",
    school: "WCAS",
    title: "Introduction to Microeconomics",
    subject: "ECON",
    number: "202-0",
  },
  {
    course_id: "001655",
    unique_id: "40153",
    school: "WCAS",
    title: "Money and Banking",
    subject: "ECON",
    number: "308-0",
  },
  {
    course_id: "001657",
    unique_id: "40154",
    school: "WCAS",
    title: "Microeconomics",
    subject: "ECON",
    number: "310-1",
  },
  {
    course_id: "001658",
    unique_id: "41868",
    school: "WCAS",
    title: "Microeconomics",
    subject: "ECON",
    number: "310-2",
  },
  {
    course_id: "001659",
    unique_id: "40155",
    school: "WCAS",
    title: "Macroeconomics",
    subject: "ECON",
    number: "311-0",
  },
  {
    course_id: "001673",
    unique_id: "40254",
    school: "WCAS",
    title: "Behavioral Economics",
    subject: "ECON",
    number: "330-0",
  },
  {
    course_id: "001679",
    unique_id: "40255",
    school: "WCAS",
    title: "Industrial Economics",
    subject: "ECON",
    number: "349-0",
  },
  {
    course_id: "001680",
    unique_id: "40256",
    school: "WCAS",
    title: "Monopoly Competition & Public Policy",
    subject: "ECON",
    number: "350-0",
  },
  {
    course_id: "022402",
    unique_id: "40257",
    school: "WCAS",
    title: "Natural Resource Economics",
    subject: "ECON",
    number: "373-0",
  },
  {
    course_id: "019446",
    unique_id: "40051",
    school: "WCAS",
    title: "Responsible Conduct of Research Training",
    subject: "ECON",
    number: "519-0",
  },
  {
    course_id: "004994",
    unique_id: "41962",
    school: "MEAS",
    title: "Special Topics in Electrical Engineering",
    subject: "ELEC_ENG",
    number: "395-0",
  },
  {
    course_id: "005010",
    unique_id: "41963",
    school: "MEAS",
    title: "Special Topics in Electrical Engineering",
    subject: "ELEC_ENG",
    number: "495-0",
  },
  {
    course_id: "022061",
    unique_id: "42319",
    school: "WCAS",
    title: "Summer Academic Workshop in Writing",
    subject: "ENGLISH",
    number: "100-SW",
  },
  {
    course_id: "001767",
    unique_id: "41446",
    school: "WCAS",
    title: "Expository Writing",
    subject: "ENGLISH",
    number: "105-0",
  },
  {
    course_id: "021465",
    unique_id: "40969",
    school: "UC",
    title: "Writing Seminar II",
    subject: "ENGLISH",
    number: "111-DL",
  },
  {
    course_id: "006181",
    unique_id: "41100",
    school: "UC",
    title: "Introduction to Literature",
    subject: "ENGLISH",
    number: "113-CN",
  },
  {
    course_id: "022206",
    unique_id: "41449",
    school: "WCAS",
    title: "Writing and Speaking in Business",
    subject: "ENGLISH",
    number: "282-0",
  },
  {
    course_id: "001791",
    unique_id: "41448",
    school: "WCAS",
    title: "Advanced Composition",
    subject: "ENGLISH",
    number: "305-0",
  },
  {
    course_id: "001792",
    unique_id: "41773",
    school: "WCAS",
    title: "Advanced Creative Writing",
    subject: "ENGLISH",
    number: "307-0",
  },
  {
    course_id: "001797",
    unique_id: "41774",
    school: "WCAS",
    title: "Studies in Fiction",
    subject: "ENGLISH",
    number: "313-0",
  },
  {
    course_id: "001844",
    unique_id: "41775",
    school: "WCAS",
    title: "Topics in Combined Studies",
    subject: "ENGLISH",
    number: "385-0",
  },
  {
    course_id: "001845",
    unique_id: "41776",
    school: "WCAS",
    title: "Studies in Literature and Film",
    subject: "ENGLISH",
    number: "386-0",
  },
  {
    course_id: "023333",
    unique_id: "42128",
    school: "WCAS",
    title: "Editorial Practicum",
    subject: "ENGLISH",
    number: "491-0",
  },
  {
    course_id: "018572",
    unique_id: "42212",
    school: "WCAS",
    title: "Special Topics in Environmental Policy and Culture",
    subject: "ENVR_POL",
    number: "390-0",
  },
  {
    course_id: "020567",
    unique_id: "42038",
    school: "WCAS",
    title: "Special Topics in Environmental Sciences",
    subject: "ENVR_SCI",
    number: "390-0",
  },
  {
    course_id: "023376",
    unique_id: "40975",
    school: "UC",
    title: "Introduction to Finance",
    subject: "FINANCE",
    number: "202-DL",
  },
  {
    course_id: "023665",
    unique_id: "41135",
    school: "UC",
    title: "FinTech Boot Camp",
    subject: "FNTEC_BC",
    number: "200-0",
  },
  {
    course_id: "023664",
    unique_id: "41134",
    school: "UC",
    title: "FinTech Boot Camp",
    subject: "FNTEC_BC",
    number: "200-0",
  },
  {
    course_id: "018840",
    unique_id: "40978",
    school: "UC",
    title: "Insurance Planning",
    subject: "FN_EXTND",
    number: "301-0",
  },
  {
    course_id: "017707",
    unique_id: "40979",
    school: "UC",
    title: "Extended Program: Investment Planning",
    subject: "FN_EXTND",
    number: "312-0",
  },
  {
    course_id: "017709",
    unique_id: "40980",
    school: "UC",
    title: "Extended Program: Retirement Planning and Employee Benefits",
    subject: "FN_EXTND",
    number: "314-0",
  },
  {
    course_id: "002987",
    unique_id: "41692",
    school: "WCAS",
    title: "Elementary French",
    subject: "FRENCH",
    number: "111-1",
  },
  {
    course_id: "002988",
    unique_id: "41693",
    school: "WCAS",
    title: "Elementary French",
    subject: "FRENCH",
    number: "111-2",
  },
  {
    course_id: "002989",
    unique_id: "41694",
    school: "WCAS",
    title: "Elementary French",
    subject: "FRENCH",
    number: "111-3",
  },
  {
    course_id: "002993",
    unique_id: "41695",
    school: "WCAS",
    title: "Intermediate French",
    subject: "FRENCH",
    number: "121-1",
  },
  {
    course_id: "002994",
    unique_id: "41696",
    school: "WCAS",
    title: "Intermediate French",
    subject: "FRENCH",
    number: "121-2",
  },
  {
    course_id: "002995",
    unique_id: "41697",
    school: "WCAS",
    title: "Intermediate French",
    subject: "FRENCH",
    number: "121-3",
  },
  {
    course_id: "021495",
    unique_id: "42213",
    school: "WCAS",
    title: "International Perspectives on Mental Health",
    subject: "GBL_HLTH",
    number: "307-0",
  },
  {
    course_id: "016805",
    unique_id: "41766",
    school: "WCAS",
    title: "Special Topics in Global Health",
    subject: "GBL_HLTH",
    number: "390-0",
  },
  {
    course_id: "021367",
    unique_id: "42204",
    school: "MEAS",
    title: "Responsible Conduct for Research Training",
    subject: "GEN_ENG",
    number: "519-0",
  },
  {
    course_id: "001955",
    unique_id: "41409",
    school: "WCAS",
    title: "Beginning German",
    subject: "GERMAN",
    number: "101-1",
  },
  {
    course_id: "001956",
    unique_id: "41410",
    school: "WCAS",
    title: "Beginning German",
    subject: "GERMAN",
    number: "101-2",
  },
  {
    course_id: "001957",
    unique_id: "41411",
    school: "WCAS",
    title: "Beginning German",
    subject: "GERMAN",
    number: "101-3",
  },
  {
    course_id: "017811",
    unique_id: "41675",
    school: "WCAS",
    title: "Gender, Sexuality, and Political Theory",
    subject: "GNDR_ST",
    number: "352-0",
  },
  {
    course_id: "017817",
    unique_id: "41676",
    school: "WCAS",
    title: "Gender, Sexuality, and Performance",
    subject: "GNDR_ST",
    number: "372-0",
  },
  {
    course_id: "003425",
    unique_id: "41827",
    school: "WCAS",
    title: "Topics in Gender and Sexuality Studies",
    subject: "GNDR_ST",
    number: "390-0",
  },
  {
    course_id: "023760",
    unique_id: "41111",
    school: "UC",
    title: "Healthcare Billing Models & Systems",
    subject: "HC_COM",
    number: "413-DL",
  },
  {
    course_id: "018651",
    unique_id: "41772",
    school: "WCAS",
    title: "New Introductory Courses in History",
    subject: "HISTORY",
    number: "200-0",
  },
  {
    course_id: "002030",
    unique_id: "41767",
    school: "WCAS",
    title: "Europe in the Medieval and Early Modern World",
    subject: "HISTORY",
    number: "201-1",
  },
  {
    course_id: "002031",
    unique_id: "41768",
    school: "WCAS",
    title: "Europe in the Modern World",
    subject: "HISTORY",
    number: "201-2",
  },
  {
    course_id: "021261",
    unique_id: "41704",
    school: "SPCH",
    title: "Special Topics in Health Communication 1",
    subject: "HLTH_COM",
    number: "469-0",
  },
  {
    course_id: "021263",
    unique_id: "41705",
    school: "SPCH",
    title:
      "Health Information Technology for Communication, Coordination and Integration",
    subject: "HLTH_COM",
    number: "479-0",
  },
  {
    course_id: "021264",
    unique_id: "41706",
    school: "SPCH",
    title: "Health Communication Practicum",
    subject: "HLTH_COM",
    number: "489-0",
  },
  {
    course_id: "022479",
    unique_id: "41470",
    school: "WCAS",
    title: "Rigor & Reproducibility in Research",
    subject: "IBIS",
    number: "421-0",
  },
  {
    course_id: "005121",
    unique_id: "42049",
    school: "MEAS",
    title: "Introduction to Statistics",
    subject: "IEMS",
    number: "201-0",
  },
  {
    course_id: "018269",
    unique_id: "41991",
    school: "JOUR",
    title: "Introduction to Integrated Marketing Communications",
    subject: "IMC",
    number: "300-0",
  },
  {
    course_id: "018308",
    unique_id: "41485",
    school: "JOUR",
    title: "Immersion Quarter Team Project",
    subject: "IMC",
    number: "409-0",
  },
  {
    course_id: "018298",
    unique_id: "41484",
    school: "JOUR",
    title: "Immersion Quarter Individual Project",
    subject: "IMC",
    number: "409-1",
  },
  {
    course_id: "023188",
    unique_id: "41487",
    school: "JOUR",
    title: "Shopper Marketing",
    subject: "IMC",
    number: "424-6",
  },
  {
    course_id: "020307",
    unique_id: "42151",
    school: "JOUR",
    title: "Crisis Communications",
    subject: "IMC",
    number: "444-6",
  },
  {
    course_id: "020310",
    unique_id: "42150",
    school: "JOUR",
    title: "Special Topics",
    subject: "IMC",
    number: "490-6",
  },
  {
    course_id: "020311",
    unique_id: "41486",
    school: "JOUR",
    title: "Practicum",
    subject: "IMC",
    number: "498-6",
  },
  {
    course_id: "023920",
    unique_id: "41431",
    school: "WCAS",
    title:
      "Development in the Global Context: Participation, Power, and Social Change",
    subject: "INTL_ST",
    number: "393-0",
  },
  {
    course_id: "021300",
    unique_id: "41920",
    school: "LAW",
    title: "Patent Preparation & Prosecution Workshop",
    subject: "INTPROP",
    number: "910-0",
  },
  {
    course_id: "013506",
    unique_id: "41142",
    school: "UC",
    title: "Special Topics",
    subject: "IPLS",
    number: "492-0",
  },
  {
    course_id: "003078",
    unique_id: "41698",
    school: "WCAS",
    title: "Elementary Italian",
    subject: "ITALIAN",
    number: "101-1",
  },
  {
    course_id: "003079",
    unique_id: "41699",
    school: "WCAS",
    title: "Elementary Italian",
    subject: "ITALIAN",
    number: "101-2",
  },
  {
    course_id: "003080",
    unique_id: "41700",
    school: "WCAS",
    title: "Elementary Italian",
    subject: "ITALIAN",
    number: "101-3",
  },
  {
    course_id: "003094",
    unique_id: "41990",
    school: "WCAS",
    title: "Italian Through Performance",
    subject: "ITALIAN",
    number: "202-0",
  },
  {
    course_id: "022682",
    unique_id: "40445",
    school: "JOUR",
    title: "Bridge Program",
    subject: "JOUR",
    number: "190-BR",
  },
  {
    course_id: "000968",
    unique_id: "40434",
    school: "JOUR",
    title: "Internship",
    subject: "JOUR",
    number: "388-0",
  },
  {
    course_id: "019985",
    unique_id: "42207",
    school: "JOUR",
    title: "Foundations of Video Journalism",
    subject: "JOUR",
    number: "400-0",
  },
  {
    course_id: "000998",
    unique_id: "42294",
    school: "JOUR",
    title: "Journalism Methods",
    subject: "JOUR",
    number: "400-1",
  },
  {
    course_id: "018037",
    unique_id: "42106",
    school: "JOUR",
    title: "Foundations of Interactive Journalism",
    subject: "JOUR",
    number: "400-3",
  },
  {
    course_id: "000971",
    unique_id: "42200",
    school: "JOUR",
    title: "Ethics & Law of Journalism",
    subject: "JOUR",
    number: "401-0",
  },
  {
    course_id: "000985",
    unique_id: "42109",
    school: "JOUR",
    title: "Health & Sciences Seminar",
    subject: "JOUR",
    number: "425-0",
  },
  {
    course_id: "001010",
    unique_id: "42201",
    school: "JOUR",
    title: "Capstone: Washington Reporting",
    subject: "JOUR",
    number: "438-1",
  },
  {
    course_id: "023596",
    unique_id: "42304",
    school: "JOUR",
    title: "Media Innovation & Content Strategy in Practice",
    subject: "JOUR",
    number: "443-0",
  },
  {
    course_id: "023755",
    unique_id: "42110",
    school: "JOUR",
    title: "Master's Project",
    subject: "JOUR",
    number: "471-0",
  },
  {
    course_id: "019652",
    unique_id: "40453",
    school: "JOUR",
    title: "Inside Business to Business Media",
    subject: "JOUR",
    number: "474-0",
  },
  {
    course_id: "019828",
    unique_id: "42296",
    school: "JOUR",
    title: "Special Topics",
    subject: "JOUR",
    number: "480-0",
  },
  {
    course_id: "001007",
    unique_id: "42113",
    school: "JOUR",
    title: "Special Topics",
    subject: "JOUR",
    number: "490-0",
  },
  {
    course_id: "022323",
    unique_id: "40444",
    school: "JOUR",
    title: "Practicum",
    subject: "JOUR",
    number: "498-0",
  },
  {
    course_id: "001006",
    unique_id: "40441",
    school: "JOUR",
    title: "Internship",
    subject: "JOUR",
    number: "499-2",
  },
  {
    course_id: "005925",
    unique_id: "41091",
    school: "UC",
    title: "Writing for Media",
    subject: "JRN_WRIT",
    number: "201-A",
  },
  {
    course_id: "002349",
    unique_id: "41478",
    school: "WCAS",
    title: "Korean I",
    subject: "KOREAN",
    number: "111-1",
  },
  {
    course_id: "002350",
    unique_id: "41479",
    school: "WCAS",
    title: "Korean I",
    subject: "KOREAN",
    number: "111-2",
  },
  {
    course_id: "002351",
    unique_id: "41480",
    school: "WCAS",
    title: "Korean I",
    subject: "KOREAN",
    number: "111-3",
  },
  {
    course_id: "018748",
    unique_id: "41708",
    school: "WCAS",
    title: "Topics in Latina and Latino Social and Political Issues",
    subject: "LATINO",
    number: "392-0",
  },
  {
    course_id: "018649",
    unique_id: "40433",
    school: "WCAS",
    title: "Topics in Latina and Latino Text and Representation",
    subject: "LATINO",
    number: "393-0",
  },
  {
    course_id: "016304",
    unique_id: "41891",
    school: "LAW",
    title: "Basics of Contract Drafting",
    subject: "LAWSTUDY",
    number: "622",
  },
  {
    course_id: "006991",
    unique_id: "41961",
    school: "LAW",
    title: "Law Practice Field Studies",
    subject: "LAWSTUDY",
    number: "659",
  },
  {
    course_id: "022768",
    unique_id: "41890",
    school: "LAW",
    title: "Advanced Legal Writing (LLM)",
    subject: "LAWSTUDY",
    number: "716",
  },
  {
    course_id: "023399",
    unique_id: "41895",
    school: "LAW",
    title: "Leading in the Law",
    subject: "LAWSTUDY",
    number: "721",
  },
  {
    course_id: "022705",
    unique_id: "42008",
    school: "LAW",
    title: "Ethics",
    subject: "LAWSTUDY",
    number: "912-0",
  },
  {
    course_id: "021724",
    unique_id: "41889",
    school: "LAW",
    title: "American Legal Studies:Civil Procedure",
    subject: "LAWSTUDY",
    number: "923",
  },
  {
    course_id: "021426",
    unique_id: "41917",
    school: "LAW",
    title: "Corporate Criminal Law",
    subject: "LAWSTUDY",
    number: "930-0",
  },
  {
    course_id: "017664",
    unique_id: "40988",
    school: "UC",
    title: "Leading, Acting, and Thinking Strategically",
    subject: "LEAD_ART",
    number: "200-0",
  },
  {
    course_id: "020333",
    unique_id: "40999",
    school: "UC",
    title: "Developing People and Teams",
    subject: "LEAD_ART",
    number: "204-0",
  },
  {
    course_id: "020156",
    unique_id: "41798",
    school: "WCAS",
    title: "Law and Society",
    subject: "LEGAL_ST",
    number: "206-0",
  },
  {
    course_id: "002391",
    unique_id: "40116",
    school: "WCAS",
    title: "Formal Analysis of Words & Sentences",
    subject: "LING",
    number: "260-0",
  },
  {
    course_id: "002390",
    unique_id: "40121",
    school: "WCAS",
    title: "Meaning",
    subject: "LING",
    number: "270-0",
  },
  {
    course_id: "002417",
    unique_id: "41443",
    school: "WCAS",
    title: "Spoken English for Nonnative Speakers",
    subject: "LING",
    number: "380-0",
  },
  {
    course_id: "002436",
    unique_id: "40117",
    school: "WCAS",
    title: "American Academic Culture for Non-Native speakers of English",
    subject: "LING",
    number: "480-0",
  },
  {
    course_id: "021793",
    unique_id: "40120",
    school: "WCAS",
    title:
      "Individual Speech and Language Instruction for Nonnative Speakers of English",
    subject: "LING",
    number: "482-0",
  },
  {
    course_id: "021792",
    unique_id: "40119",
    school: "WCAS",
    title: "Supported Online Speech Training for Nonnative Speakers of English",
    subject: "LING",
    number: "483-0",
  },
  {
    course_id: "023404",
    unique_id: "41078",
    school: "UC",
    title: "Topics in Comparative Literature",
    subject: "LIT",
    number: "480-DL",
  },
  {
    course_id: "021237",
    unique_id: "41894",
    school: "LAW",
    title: "Legal Ethics in a Global Legal Practice",
    subject: "LITARB",
    number: "600G",
  },
  {
    course_id: "021581",
    unique_id: "41905",
    school: "LAW",
    title: "International Business Law & Negotiations",
    subject: "LITARB",
    number: "604T",
  },
  {
    course_id: "022952",
    unique_id: "41907",
    school: "LAW",
    title: "Negotiation Workshop",
    subject: "LITARB",
    number: "670S",
  },
  {
    course_id: "019158",
    unique_id: "41901",
    school: "LAW",
    title: "Clinic Practice: Complex Civil Litigation & Investor Protection",
    subject: "LITARB",
    number: "730",
  },
  {
    course_id: "021747",
    unique_id: "41820",
    school: "WCAS",
    title: "Quantitative Reasoning",
    subject: "MATH",
    number: "100-BR",
  },
  {
    course_id: "023340",
    unique_id: "41821",
    school: "WCAS",
    title: "Single-Variable Differential Calculus",
    subject: "MATH",
    number: "220-1",
  },
  {
    course_id: "023341",
    unique_id: "41822",
    school: "WCAS",
    title: "Single-Variable Integral Calculus",
    subject: "MATH",
    number: "220-2",
  },
  {
    course_id: "023345",
    unique_id: "41823",
    school: "WCAS",
    title: "Multivariable Differential Calculus",
    subject: "MATH",
    number: "230-1",
  },
  {
    course_id: "023346",
    unique_id: "41824",
    school: "WCAS",
    title: "Multivariable Integral Calculus",
    subject: "MATH",
    number: "230-2",
  },
  {
    course_id: "008660",
    unique_id: "41819",
    school: "WCAS",
    title: "Linear Algebra",
    subject: "MATH",
    number: "240-0",
  },
  {
    course_id: "002472",
    unique_id: "41815",
    school: "WCAS",
    title: "Foundations of Higher Mathematics",
    subject: "MATH",
    number: "300-0",
  },
  {
    course_id: "002492",
    unique_id: "41816",
    school: "WCAS",
    title: "Linear Algebra: Second Course",
    subject: "MATH",
    number: "334-0",
  },
  {
    course_id: "022539",
    unique_id: "41588",
    school: "MEAS",
    title: "MS Thesis Research",
    subject: "MAT_SCI",
    number: "596-0",
  },
  {
    course_id: "016320",
    unique_id: "41862",
    school: "MEAS",
    title: "Biotechnology Research",
    subject: "MBIOTECH",
    number: "510-0",
  },
  {
    course_id: "016182",
    unique_id: "41948",
    school: "UC",
    title: "Fiction Workshop",
    subject: "MCW",
    number: "413-0",
  },
  {
    course_id: "016183",
    unique_id: "41947",
    school: "UC",
    title: "Creative Non-Fiction Workshop",
    subject: "MCW",
    number: "461-0",
  },
  {
    course_id: "017669",
    unique_id: "40981",
    school: "UC",
    title: "Mediation Skills Training",
    subject: "MED_SKIL",
    number: "100-0",
  },
  {
    course_id: "021838",
    unique_id: "41071",
    school: "UC",
    title: "Fundamentals of Health Informatics",
    subject: "MHI",
    number: "403-DL",
  },
  {
    course_id: "018092",
    unique_id: "41069",
    school: "UC",
    title: "Decision Support Systems and Health Care",
    subject: "MHI",
    number: "406-DL",
  },
  {
    course_id: "017853",
    unique_id: "41068",
    school: "UC",
    title: "Information System Acquisition & Lifecycle",
    subject: "MHI",
    number: "408-DL",
  },
  {
    course_id: "021839",
    unique_id: "41926",
    school: "UC",
    title: "Consumer Digital Health",
    subject: "MHI",
    number: "413-DL",
  },
  {
    course_id: "022453",
    unique_id: "40970",
    school: "UC",
    title: "Principles of Marketing",
    subject: "MKTG",
    number: "201-DL",
  },
  {
    course_id: "022309",
    unique_id: "41101",
    school: "UC",
    title: "Brand Management",
    subject: "MKTG",
    number: "320-CN",
  },
  {
    course_id: "018585",
    unique_id: "41067",
    school: "UC",
    title: "Elements of Public Finance and Budgeting",
    subject: "MPPA",
    number: "402-DL",
  },
  {
    course_id: "018591",
    unique_id: "41066",
    school: "UC",
    title: "Microeconomics for Public Policy Administration",
    subject: "MPPA",
    number: "404-DL",
  },
  {
    course_id: "018592",
    unique_id: "41935",
    school: "UC",
    title: "Statistics for Research",
    subject: "MPPA",
    number: "405-DL",
  },
  {
    course_id: "018593",
    unique_id: "41064",
    school: "UC",
    title: "Program Evaluation and Policy Analysis",
    subject: "MPPA",
    number: "406-DL",
  },
  {
    course_id: "018594",
    unique_id: "41062",
    school: "UC",
    title: "Scope and Theory of Public Policy",
    subject: "MPPA",
    number: "407-DL",
  },
  {
    course_id: "016585",
    unique_id: "41117",
    school: "UC",
    title: "Public Organization Theory and Management",
    subject: "MPPA",
    number: "408-0",
  },
  {
    course_id: "022892",
    unique_id: "41061",
    school: "UC",
    title: "Ethics and Leadership",
    subject: "MPPA",
    number: "418-DL",
  },
  {
    course_id: "023650",
    unique_id: "41120",
    school: "UC",
    title: "Administrative Law",
    subject: "MPPA",
    number: "421-DL",
  },
  {
    course_id: "022254",
    unique_id: "41060",
    school: "UC",
    title: "Behavioral Economics",
    subject: "MPPA",
    number: "430-0",
  },
  {
    course_id: "022253",
    unique_id: "41936",
    school: "UC",
    title: "Behavioral Economics",
    subject: "MPPA",
    number: "430-DL",
  },
  {
    course_id: "020971",
    unique_id: "41937",
    school: "UC",
    title: "Intergovernmental Relations",
    subject: "MPPA",
    number: "432-0",
  },
  {
    course_id: "020631",
    unique_id: "41059",
    school: "UC",
    title: "International Institutions",
    subject: "MPPA",
    number: "440-DL",
  },
  {
    course_id: "020741",
    unique_id: "41110",
    school: "UC",
    title: "The Capstone Project",
    subject: "MPPA",
    number: "498-0",
  },
  {
    course_id: "018600",
    unique_id: "41058",
    school: "UC",
    title: "The Capstone Project",
    subject: "MPPA",
    number: "498-DL",
  },
  {
    course_id: "022271",
    unique_id: "41122",
    school: "UC",
    title: "Introduction to Sports Analytics",
    subject: "MSA",
    number: "401-DL",
  },
  {
    course_id: "022835",
    unique_id: "41992",
    school: "UC",
    title: "Fundamentals of Sports Marketing",
    subject: "MSA",
    number: "402-DL",
  },
  {
    course_id: "022387",
    unique_id: "41057",
    school: "UC",
    title: "Sports Organizations: Leadership Theory & Application",
    subject: "MSA",
    number: "403-DL",
  },
  {
    course_id: "022458",
    unique_id: "41997",
    school: "UC",
    title: "Sports Business: Finance, Accounting and Economics",
    subject: "MSA",
    number: "404-DL",
  },
  {
    course_id: "022386",
    unique_id: "41125",
    school: "UC",
    title: "Legal and Ethical Issues in Sports Management",
    subject: "MSA",
    number: "405-DL",
  },
  {
    course_id: "022009",
    unique_id: "41939",
    school: "UC",
    title: "Sports Public Relations and Crisis Management",
    subject: "MSA",
    number: "406-DL",
  },
  {
    course_id: "024040",
    unique_id: "41940",
    school: "UC",
    title: "Event Management for Sports",
    subject: "MSA",
    number: "424-DL",
  },
  {
    course_id: "021842",
    unique_id: "41056",
    school: "UC",
    title: "The Technology of Sport",
    subject: "MSA",
    number: "451-DL",
  },
  {
    course_id: "017881",
    unique_id: "41941",
    school: "UC",
    title: "Special Topics",
    subject: "MSA",
    number: "490-0",
  },
  {
    course_id: "019179",
    unique_id: "41127",
    school: "UC",
    title: "Capstone Class",
    subject: "MSA",
    number: "498-0",
  },
  {
    course_id: "015460",
    unique_id: "42107",
    school: "SPCH",
    title: "Public Persuasion",
    subject: "MSC",
    number: "482-0",
  },
  {
    course_id: "022106",
    unique_id: "42027",
    school: "SPCH",
    title: "Communication Skills Practicum",
    subject: "MSC",
    number: "494-6D",
  },
  {
    course_id: "004308",
    unique_id: "42077",
    school: "SPCH",
    title: "Leadership & Decision Making",
    subject: "MSC",
    number: "496-0",
  },
  {
    course_id: "022350",
    unique_id: "42079",
    school: "SPCH",
    title: "Capstone",
    subject: "MSC",
    number: "523-0",
  },
  {
    course_id: "022095",
    unique_id: "42026",
    school: "SPCH",
    title: "Capstone",
    subject: "MSC",
    number: "523-6",
  },
  {
    course_id: "019880",
    unique_id: "42025",
    school: "SPCH",
    title: "Communication, Management & Ethics",
    subject: "MSC",
    number: "530-0",
  },
  {
    course_id: "022237",
    unique_id: "42028",
    school: "SPCH",
    title: "Workplace Learning and Communities of Practice",
    subject: "MSC",
    number: "538-0",
  },
  {
    course_id: "022400",
    unique_id: "42029",
    school: "SPCH",
    title: "Content & Influencer Marketing Communication",
    subject: "MSC",
    number: "539-0",
  },
  {
    course_id: "022776",
    unique_id: "41007",
    school: "UC",
    title: "Math For Data Scientists",
    subject: "MSDS",
    number: "400-DL",
  },
  {
    course_id: "022777",
    unique_id: "41013",
    school: "UC",
    title: "Applied Statistics with R",
    subject: "MSDS",
    number: "401-DL",
  },
  {
    course_id: "022778",
    unique_id: "41016",
    school: "UC",
    title: "Introduction to Data Science",
    subject: "MSDS",
    number: "402-DL",
  },
  {
    course_id: "023637",
    unique_id: "42122",
    school: "UC",
    title: "Data Science in Practice",
    subject: "MSDS",
    number: "403-DL",
  },
  {
    course_id: "022779",
    unique_id: "41018",
    school: "UC",
    title: "Supervised Learning Methods",
    subject: "MSDS",
    number: "410-DL",
  },
  {
    course_id: "022780",
    unique_id: "41114",
    school: "UC",
    title: "Unsupervised Learning Methods",
    subject: "MSDS",
    number: "411-DL",
  },
  {
    course_id: "022781",
    unique_id: "41020",
    school: "UC",
    title: "Times Series Analysis and Forecasting",
    subject: "MSDS",
    number: "413-DL",
  },
  {
    course_id: "022782",
    unique_id: "41023",
    school: "UC",
    title: "Database Systems and Data Preparation",
    subject: "MSDS",
    number: "420-DL",
  },
  {
    course_id: "022783",
    unique_id: "41026",
    school: "UC",
    title: "Practical Machine Learning",
    subject: "MSDS",
    number: "422-DL",
  },
  {
    course_id: "022784",
    unique_id: "41928",
    school: "UC",
    title: "Python for Data Analysis",
    subject: "MSDS",
    number: "430-DL",
  },
  {
    course_id: "022785",
    unique_id: "41030",
    school: "UC",
    title: "Foundations for Data Engineering",
    subject: "MSDS",
    number: "432-DL",
  },
  {
    course_id: "022786",
    unique_id: "41929",
    school: "UC",
    title: "Analytics Application Engineering",
    subject: "MSDS",
    number: "434-DL",
  },
  {
    course_id: "023493",
    unique_id: "41930",
    school: "UC",
    title: "Real-Time Interactive Processing and Analytics",
    subject: "MSDS",
    number: "440-DL",
  },
  {
    course_id: "022790",
    unique_id: "41031",
    school: "UC",
    title: "Web and Network Data Science",
    subject: "MSDS",
    number: "452-DL",
  },
  {
    course_id: "022791",
    unique_id: "41116",
    school: "UC",
    title: "Natural Language Processing",
    subject: "MSDS",
    number: "453-DL",
  },
  {
    course_id: "022793",
    unique_id: "41033",
    school: "UC",
    title: "Data Visualization",
    subject: "MSDS",
    number: "455-DL",
  },
  {
    course_id: "022794",
    unique_id: "41034",
    school: "UC",
    title: "Sports Performance Analytics",
    subject: "MSDS",
    number: "456-DL",
  },
  {
    course_id: "022796",
    unique_id: "41036",
    school: "UC",
    title: "Artificial Intelligence and Deep Learning",
    subject: "MSDS",
    number: "458-DL",
  },
  {
    course_id: "022798",
    unique_id: "41039",
    school: "UC",
    title: "Decision Analytics",
    subject: "MSDS",
    number: "460-DL",
  },
  {
    course_id: "023364",
    unique_id: "41931",
    school: "UC",
    title: "Intelligent Systems and Robotics",
    subject: "MSDS",
    number: "464-DL",
  },
  {
    course_id: "022799",
    unique_id: "41932",
    school: "UC",
    title: "Analytics Entrepreneurship",
    subject: "MSDS",
    number: "470-DL",
  },
  {
    course_id: "022801",
    unique_id: "41040",
    school: "UC",
    title: "Accounting and Finance for Analytics Managers",
    subject: "MSDS",
    number: "474-DL",
  },
  {
    course_id: "022802",
    unique_id: "41042",
    school: "UC",
    title: "Project Management",
    subject: "MSDS",
    number: "475-DL",
  },
  {
    course_id: "022803",
    unique_id: "41044",
    school: "UC",
    title: "Business Leadership and Communications",
    subject: "MSDS",
    number: "480-DL",
  },
  {
    course_id: "023912",
    unique_id: "41933",
    school: "UC",
    title: "Data Governance, Ethics, and Law",
    subject: "MSDS",
    number: "485-DL",
  },
  {
    course_id: "022808",
    unique_id: "41138",
    school: "UC",
    title: "Capstone Class",
    subject: "MSDS",
    number: "498-DL",
  },
  {
    course_id: "021129",
    unique_id: "41055",
    school: "UC",
    title: "Research Methods",
    subject: "MSGH",
    number: "410-DL",
  },
  {
    course_id: "021130",
    unique_id: "41006",
    school: "UC",
    title: "Global Health Systems",
    subject: "MSGH",
    number: "417-DL",
  },
  {
    course_id: "021122",
    unique_id: "41054",
    school: "UC",
    title: "Sustainability of Global Health Initiatives",
    subject: "MSGH",
    number: "450-DL",
  },
  {
    course_id: "023862",
    unique_id: "41921",
    school: "UC",
    title: "Global Health Leadership",
    subject: "MSGH",
    number: "480-DL",
  },
  {
    course_id: "021433",
    unique_id: "41008",
    school: "UC",
    title: "Practicum Course",
    subject: "MSGH",
    number: "580-DL",
  },
  {
    course_id: "023431",
    unique_id: "41922",
    school: "UC",
    title: "Programming for Health Analytics",
    subject: "MSHA",
    number: "401-DL",
  },
  {
    course_id: "023592",
    unique_id: "41923",
    school: "UC",
    title: "Data Literacy and Analytics in Healthcare",
    subject: "MSHA",
    number: "405-DL",
  },
  {
    course_id: "023593",
    unique_id: "41128",
    school: "UC",
    title: "Data Security, Ethics and Governance",
    subject: "MSHA",
    number: "407-DL",
  },
  {
    course_id: "023594",
    unique_id: "41924",
    school: "UC",
    title: "Regression and Multivariate Analysis",
    subject: "MSHA",
    number: "410-DL",
  },
  {
    course_id: "023715",
    unique_id: "41925",
    school: "UC",
    title: "Artificial Intelligence and Practical Machine Learning",
    subject: "MSHA",
    number: "422-DL",
  },
  {
    course_id: "021648",
    unique_id: "41427",
    school: "SPCH",
    title: "Summer Internship Seminar",
    subject: "MSLCE",
    number: "497-0",
  },
  {
    course_id: "022250",
    unique_id: "41429",
    school: "SPCH",
    title: "MSLCE Thesis",
    subject: "MSLCE",
    number: "498-0",
  },
  {
    course_id: "021233",
    unique_id: "41879",
    school: "SPCH",
    title: "Special Topics in Creative Enterprises",
    subject: "MSLCE",
    number: "529-0",
  },
  {
    course_id: "023242",
    unique_id: "41430",
    school: "SPCH",
    title: "Independent Study",
    subject: "MSLCE",
    number: "598-0",
  },
  {
    course_id: "021651",
    unique_id: "41428",
    school: "SPCH",
    title: "Internship Experience",
    subject: "MSLCE",
    number: "599-0",
  },
  {
    course_id: "023378",
    unique_id: "41053",
    school: "UC",
    title: "Applied Research and Writing",
    subject: "MSRC",
    number: "405-DL",
  },
  {
    course_id: "022092",
    unique_id: "41052",
    school: "UC",
    title: "Risk and Decision Management",
    subject: "MSRC",
    number: "435-DL",
  },
  {
    course_id: "023821",
    unique_id: "42009",
    school: "UC",
    title: "Introduction to Data Science",
    subject: "MS_DSP",
    number: "402-DL",
  },
  {
    course_id: "023829",
    unique_id: "42010",
    school: "UC",
    title: "Python for Data Science",
    subject: "MS_DSP",
    number: "430-DL",
  },
  {
    course_id: "000804",
    unique_id: "42078",
    school: "SESP",
    title: "Social Contexts of Education",
    subject: "MS_ED",
    number: "402-0",
  },
  {
    course_id: "021571",
    unique_id: "41842",
    school: "SESP",
    title: "Child and Adolescent Development",
    subject: "MS_ED",
    number: "405-0",
  },
  {
    course_id: "021816",
    unique_id: "41843",
    school: "SESP",
    title: "Foundations of Learning in a New Language",
    subject: "MS_ED",
    number: "410-0",
  },
  {
    course_id: "022029",
    unique_id: "41845",
    school: "SESP",
    title: "Mathematics for Elementary Teachers",
    subject: "MS_ED",
    number: "414-0",
  },
  {
    course_id: "015585",
    unique_id: "41909",
    school: "SESP",
    title: "Content Area Reading and Writing for Elementary Teachers",
    subject: "MS_ED",
    number: "421-0",
  },
  {
    course_id: "015574",
    unique_id: "41837",
    school: "SESP",
    title: "Content Area Reading and Writing",
    subject: "MS_ED",
    number: "422-0",
  },
  {
    course_id: "015392",
    unique_id: "41836",
    school: "SESP",
    title: "Instructional Coaching and Evaluation",
    subject: "MS_ED",
    number: "431-0",
  },
  {
    course_id: "000822",
    unique_id: "41866",
    school: "SESP",
    title: "Topics in Teaching and Learning",
    subject: "MS_ED",
    number: "451-0",
  },
  {
    course_id: "021927",
    unique_id: "41844",
    school: "SESP",
    title: "Professional Development Design & Implementation",
    subject: "MS_ED",
    number: "462-0",
  },
  {
    course_id: "023646",
    unique_id: "41846",
    school: "SESP",
    title: "Leading for Equity",
    subject: "MS_ED",
    number: "463-0",
  },
  {
    course_id: "000830",
    unique_id: "41833",
    school: "SESP",
    title: "Proseminar in Higher Education",
    subject: "MS_HE",
    number: "460-0",
  },
  {
    course_id: "019840",
    unique_id: "41839",
    school: "SESP",
    title: "Structure, Governance and Leadership in Higher Education",
    subject: "MS_HE",
    number: "473-0",
  },
  {
    course_id: "022412",
    unique_id: "42045",
    school: "SESP",
    title: "Global Issues and Strategics Partnerships",
    subject: "MS_HE",
    number: "478-0",
  },
  {
    course_id: "023693",
    unique_id: "41847",
    school: "SESP",
    title:
      "Advancing Diversity and Inclusion Through Intentional Leadership and Organizational Change",
    subject: "MS_HE",
    number: "479-0",
  },
  {
    course_id: "019843",
    unique_id: "41840",
    school: "SESP",
    title: "Internship in Higher Education",
    subject: "MS_HE",
    number: "485-0",
  },
  {
    course_id: "021532",
    unique_id: "41106",
    school: "UC",
    title: "Models and Theories of User-Centered Design",
    subject: "MS_IDS",
    number: "401-DL",
  },
  {
    course_id: "021533",
    unique_id: "41942",
    school: "UC",
    title: "Effective Communication",
    subject: "MS_IDS",
    number: "403-DL",
  },
  {
    course_id: "021534",
    unique_id: "41009",
    school: "UC",
    title: "User Research",
    subject: "MS_IDS",
    number: "405-DL",
  },
  {
    course_id: "021536",
    unique_id: "41051",
    school: "UC",
    title: "Information and Content Strategy",
    subject: "MS_IDS",
    number: "407-DL",
  },
  {
    course_id: "021537",
    unique_id: "41010",
    school: "UC",
    title: "Data Science, Management, and Business Strategy",
    subject: "MS_IDS",
    number: "409-DL",
  },
  {
    course_id: "021538",
    unique_id: "41943",
    school: "UC",
    title: "Information Design and Architecture",
    subject: "MS_IDS",
    number: "411-DL",
  },
  {
    course_id: "021539",
    unique_id: "41050",
    school: "UC",
    title: "Visual Communication",
    subject: "MS_IDS",
    number: "413-DL",
  },
  {
    course_id: "021540",
    unique_id: "41049",
    school: "UC",
    title: "Introduction to Learning Theory",
    subject: "MS_IDS",
    number: "422-DL",
  },
  {
    course_id: "021545",
    unique_id: "41048",
    school: "UC",
    title: "Persuasion and Strategic Communication",
    subject: "MS_IDS",
    number: "435-DL",
  },
  {
    course_id: "021547",
    unique_id: "41139",
    school: "UC",
    title: "Introduction to Techniques of  Predictive Analytics",
    subject: "MS_IDS",
    number: "453-DL",
  },
  {
    course_id: "021549",
    unique_id: "41944",
    school: "UC",
    title: "Visualization of Data and Text",
    subject: "MS_IDS",
    number: "455-DL",
  },
  {
    course_id: "023924",
    unique_id: "41945",
    school: "UC",
    title: "Leadership and Business Strategy",
    subject: "MS_IDS",
    number: "481-DL",
  },
  {
    course_id: "015695",
    unique_id: "41810",
    school: "SESP",
    title: "Advancing Learning & Performance Solutions",
    subject: "MS_LOC",
    number: "421-0",
  },
  {
    course_id: "015500",
    unique_id: "41808",
    school: "SESP",
    title: "Executing Strategic Change",
    subject: "MS_LOC",
    number: "440-0",
  },
  {
    course_id: "015577",
    unique_id: "41809",
    school: "SESP",
    title: "Designing Sustainable Strategic Change",
    subject: "MS_LOC",
    number: "441-0",
  },
  {
    course_id: "015484",
    unique_id: "41807",
    school: "SESP",
    title: "Building Transformational Client Relationships",
    subject: "MS_LOC",
    number: "451-0",
  },
  {
    course_id: "023028",
    unique_id: "41814",
    school: "SESP",
    title: "Designing Solutions for Organizational Effectiveness",
    subject: "MS_LOC",
    number: "456-0",
  },
  {
    course_id: "015700",
    unique_id: "41811",
    school: "SESP",
    title: "Capstone II: Design & Measurement",
    subject: "MS_LOC",
    number: "462-0",
  },
  {
    course_id: "019048",
    unique_id: "41812",
    school: "SESP",
    title: "MSLOC Internship",
    subject: "MS_LOC",
    number: "495-0",
  },
  {
    course_id: "020131",
    unique_id: "41813",
    school: "SESP",
    title: "Independent Study",
    subject: "MS_LOC",
    number: "499-1",
  },
  {
    course_id: "017670",
    unique_id: "40982",
    school: "UC",
    title: "Museum Origins and Issues",
    subject: "MUSEUM",
    number: "370-DL",
  },
  {
    course_id: "017671",
    unique_id: "41976",
    school: "UC",
    title: "Successful Museum Management in Today's Environment",
    subject: "MUSEUM",
    number: "371-DL",
  },
  {
    course_id: "017672",
    unique_id: "40983",
    school: "UC",
    title: "Learning and Museums",
    subject: "MUSEUM",
    number: "372-DL",
  },
  {
    course_id: "023521",
    unique_id: "41104",
    school: "UC",
    title: "Organization Behavior",
    subject: "ORG_BEH",
    number: "301-DL",
  },
  {
    course_id: "018337",
    unique_id: "41102",
    school: "UC",
    title: "Leadership Principles and Practices",
    subject: "ORG_BEH",
    number: "307-CN",
  },
  {
    course_id: "005864",
    unique_id: "40971",
    school: "UC",
    title: "Organizational Change",
    subject: "ORG_BEH",
    number: "310-CN",
  },
  {
    course_id: "022452",
    unique_id: "40972",
    school: "UC",
    title: "Strategic Planning and Management",
    subject: "ORG_BEH",
    number: "367-DL",
  },
  {
    course_id: "024022",
    unique_id: "41826",
    school: "UC",
    title: "Project Management",
    subject: "ORG_BEH",
    number: "368-DL",
  },
  {
    course_id: "022451",
    unique_id: "40973",
    school: "UC",
    title: "Practicum",
    subject: "ORG_BEH",
    number: "395-CN",
  },
  {
    course_id: "020372",
    unique_id: "41445",
    school: "SPCH",
    title: "Performance Culture and Communication",
    subject: "PERF_ST",
    number: "203-0",
  },
  {
    course_id: "004171",
    unique_id: "42075",
    school: "SPCH",
    title: "Topics in Performance Studies",
    subject: "PERF_ST",
    number: "330-0",
  },
  {
    course_id: "002596",
    unique_id: "41432",
    school: "WCAS",
    title: "Introduction to Philosophy",
    subject: "PHIL",
    number: "110-0",
  },
  {
    course_id: "002602",
    unique_id: "41433",
    school: "WCAS",
    title: "History of Philosophy - Ancient",
    subject: "PHIL",
    number: "210-1",
  },
  {
    course_id: "019742",
    unique_id: "41441",
    school: "WCAS",
    title: "Minds and Machines",
    subject: "PHIL",
    number: "225-0",
  },
  {
    course_id: "019741",
    unique_id: "41440",
    school: "WCAS",
    title: "Introduction to Metaphysics",
    subject: "PHIL",
    number: "259-0",
  },
  {
    course_id: "002609",
    unique_id: "41434",
    school: "WCAS",
    title: "Introduction to Moral Philosophy",
    subject: "PHIL",
    number: "260-0",
  },
  {
    course_id: "008550",
    unique_id: "41437",
    school: "WCAS",
    title: "Ethical Problems and Public Issues",
    subject: "PHIL",
    number: "262-0",
  },
  {
    course_id: "002613",
    unique_id: "41436",
    school: "WCAS",
    title: "Philosophy of Religion",
    subject: "PHIL",
    number: "266-0",
  },
  {
    course_id: "016061",
    unique_id: "41439",
    school: "WCAS",
    title: "Ethics and the Environment",
    subject: "PHIL",
    number: "268-0",
  },
  {
    course_id: "015860",
    unique_id: "41438",
    school: "WCAS",
    title: "Bioethics",
    subject: "PHIL",
    number: "269-0",
  },
  {
    course_id: "020921",
    unique_id: "41140",
    school: "UC",
    title: "Donor Psychology and the Ask",
    subject: "PHIL_NP",
    number: "315-0",
  },
  {
    course_id: "023869",
    unique_id: "41977",
    school: "UC",
    title: "Nonprofit Resilience and Reinvention Through a Crisis",
    subject: "PHIL_NP",
    number: "335-0",
  },
  {
    course_id: "018238",
    unique_id: "41151",
    school: "UC",
    title: "Grantsmanship for Research Professionals",
    subject: "PHIL_NP",
    number: "380-0",
  },
  {
    course_id: "002703",
    unique_id: "40156",
    school: "WCAS",
    title: "College Physics",
    subject: "PHYSICS",
    number: "130-1",
  },
  {
    course_id: "002704",
    unique_id: "40157",
    school: "WCAS",
    title: "College Physics",
    subject: "PHYSICS",
    number: "130-2",
  },
  {
    course_id: "002705",
    unique_id: "40158",
    school: "WCAS",
    title: "College Physics",
    subject: "PHYSICS",
    number: "130-3",
  },
  {
    course_id: "002706",
    unique_id: "40159",
    school: "WCAS",
    title: "General Physics",
    subject: "PHYSICS",
    number: "135-1",
  },
  {
    course_id: "002707",
    unique_id: "40160",
    school: "WCAS",
    title: "General Physics",
    subject: "PHYSICS",
    number: "135-2",
  },
  {
    course_id: "002708",
    unique_id: "40161",
    school: "WCAS",
    title: "General Physics",
    subject: "PHYSICS",
    number: "135-3",
  },
  {
    course_id: "021527",
    unique_id: "40223",
    school: "WCAS",
    title: "General Physics Laboratory",
    subject: "PHYSICS",
    number: "136-1",
  },
  {
    course_id: "021528",
    unique_id: "40217",
    school: "WCAS",
    title: "General Physics Laboratory",
    subject: "PHYSICS",
    number: "136-2",
  },
  {
    course_id: "021529",
    unique_id: "40220",
    school: "WCAS",
    title: "General Physics Laboratory",
    subject: "PHYSICS",
    number: "136-3",
  },
  {
    course_id: "002768",
    unique_id: "41825",
    school: "WCAS",
    title: "American Government and Politics",
    subject: "POLI_SCI",
    number: "220-0",
  },
  {
    course_id: "017872",
    unique_id: "41713",
    school: "WCAS",
    title: "Classical Political Theory",
    subject: "POLI_SCI",
    number: "301-0",
  },
  {
    course_id: "020037",
    unique_id: "41714",
    school: "WCAS",
    title: "Politics of Post-Soviet Russia",
    subject: "POLI_SCI",
    number: "369-0",
  },
  {
    course_id: "020515",
    unique_id: "41715",
    school: "WCAS",
    title: "Drugs and Politics",
    subject: "POLI_SCI",
    number: "377-0",
  },
  {
    course_id: "021554",
    unique_id: "41878",
    school: "WCAS",
    title: "America and the World",
    subject: "POLI_SCI",
    number: "378-0",
  },
  {
    course_id: "002818",
    unique_id: "41710",
    school: "WCAS",
    title: "Special Topics in Political Science",
    subject: "POLI_SCI",
    number: "390-0",
  },
  {
    course_id: "002820",
    unique_id: "41712",
    school: "WCAS",
    title: "Political Research Seminar",
    subject: "POLI_SCI",
    number: "395-0",
  },
  {
    course_id: "003127",
    unique_id: "41981",
    school: "WCAS",
    title: "Elementary Portuguese",
    subject: "PORT",
    number: "101-1",
  },
  {
    course_id: "003128",
    unique_id: "41982",
    school: "WCAS",
    title: "Elementary Portuguese",
    subject: "PORT",
    number: "101-2",
  },
  {
    course_id: "003129",
    unique_id: "41984",
    school: "WCAS",
    title: "Elementary Portuguese",
    subject: "PORT",
    number: "101-3",
  },
  {
    course_id: "020484",
    unique_id: "41000",
    school: "UC",
    title: "Developing People and Teams",
    subject: "PROJ_PMI",
    number: "204-0",
  },
  {
    course_id: "021523",
    unique_id: "40984",
    school: "UC",
    title: "Power Excel Skills for Project Managers",
    subject: "PROJ_PMI",
    number: "225-0",
  },
  {
    course_id: "023424",
    unique_id: "41080",
    school: "UC",
    title: "Practical Project Planning",
    subject: "PROJ_PMI",
    number: "345-DL",
  },
  {
    course_id: "021500",
    unique_id: "40985",
    school: "UC",
    title: "Supporting an Agile Transformation",
    subject: "PROJ_PMI",
    number: "365-0",
  },
  {
    course_id: "020382",
    unique_id: "41979",
    school: "UC",
    title: "Essentials of Project Management",
    subject: "PROJ_PMI",
    number: "401-0",
  },
  {
    course_id: "023652",
    unique_id: "41141",
    school: "UC",
    title: "Essentials of Project Management",
    subject: "PROJ_PMI",
    number: "401-DL",
  },
  {
    course_id: "020383",
    unique_id: "41978",
    school: "UC",
    title: "Applied Project Management",
    subject: "PROJ_PMI",
    number: "402-0",
  },
  {
    course_id: "022015",
    unique_id: "40986",
    school: "UC",
    title: "Applied Project Management",
    subject: "PROJ_PMI",
    number: "402-DL",
  },
  {
    course_id: "021327",
    unique_id: "40987",
    school: "UC",
    title: "Agile for Practitioners",
    subject: "PROJ_PMI",
    number: "403-0",
  },
  {
    course_id: "022286",
    unique_id: "41085",
    school: "UC",
    title: "Professional Health Careers Proseminar I",
    subject: "PRO_HLTH",
    number: "396-A",
  },
  {
    course_id: "002874",
    unique_id: "41756",
    school: "WCAS",
    title: "Introduction to Psychology",
    subject: "PSYCH",
    number: "110-0",
  },
  {
    course_id: "002875",
    unique_id: "41757",
    school: "WCAS",
    title: "Statistical Methods in Psychology",
    subject: "PSYCH",
    number: "201-0",
  },
  {
    course_id: "002876",
    unique_id: "41758",
    school: "WCAS",
    title: "Social Psychology",
    subject: "PSYCH",
    number: "213-0",
  },
  {
    course_id: "023475",
    unique_id: "41105",
    school: "UC",
    title: "Social Psychology",
    subject: "PSYCH",
    number: "213-CN",
  },
  {
    course_id: "002879",
    unique_id: "41759",
    school: "WCAS",
    title: "Psychology of Personality",
    subject: "PSYCH",
    number: "215-0",
  },
  {
    course_id: "002881",
    unique_id: "41760",
    school: "WCAS",
    title: "Cognitive Psychology",
    subject: "PSYCH",
    number: "228-0",
  },
  {
    course_id: "002884",
    unique_id: "41761",
    school: "WCAS",
    title: "Psychopathology",
    subject: "PSYCH",
    number: "303-0",
  },
  {
    course_id: "022516",
    unique_id: "41764",
    school: "WCAS",
    title: "Positive Psychology: The Science of Well-Being",
    subject: "PSYCH",
    number: "341-0",
  },
  {
    course_id: "002895",
    unique_id: "41762",
    school: "WCAS",
    title: "Social and Personality Development",
    subject: "PSYCH",
    number: "364-0",
  },
  {
    course_id: "019120",
    unique_id: "41763",
    school: "WCAS",
    title: "Child Psychopathology",
    subject: "PSYCH",
    number: "367-0",
  },
  {
    course_id: "023401",
    unique_id: "41047",
    school: "UC",
    title: "Practical Quality Management",
    subject: "QARS",
    number: "420-DL",
  },
  {
    course_id: "002218",
    unique_id: "41669",
    school: "WCAS",
    title: "Introduction to Religion",
    subject: "RELIGION",
    number: "170-0",
  },
  {
    course_id: "002226",
    unique_id: "41670",
    school: "WCAS",
    title: "Introduction to Judaism",
    subject: "RELIGION",
    number: "230-0",
  },
  {
    course_id: "002257",
    unique_id: "41671",
    school: "WCAS",
    title: "Topics in Comparative Religion",
    subject: "RELIGION",
    number: "379-0",
  },
  {
    course_id: "004336",
    unique_id: "40271",
    school: "SPCH",
    title: "Analyzing Media Texts",
    subject: "RTVF",
    number: "220-0",
  },
  {
    course_id: "015210",
    unique_id: "40272",
    school: "SPCH",
    title: "Foundations of Screenwriting",
    subject: "RTVF",
    number: "260-0",
  },
  {
    course_id: "004343",
    unique_id: "41592",
    school: "SPCH",
    title: "Studies in Media Topics",
    subject: "RTVF",
    number: "298-0",
  },
  {
    course_id: "004373",
    unique_id: "40262",
    school: "SPCH",
    title: "Topics in Media Writing",
    subject: "RTVF",
    number: "360-0",
  },
  {
    course_id: "011778",
    unique_id: "41593",
    school: "SPCH",
    title: "Topics in Interactive Media",
    subject: "RTVF",
    number: "376-0",
  },
  {
    course_id: "021674",
    unique_id: "40269",
    school: "SPCH",
    title: "Topics in Post-Production",
    subject: "RTVF",
    number: "378-0",
  },
  {
    course_id: "022181",
    unique_id: "42141",
    school: "SPCH",
    title: "Summer Internship Seminar",
    subject: "RTVF",
    number: "490-1",
  },
  {
    course_id: "022474",
    unique_id: "42152",
    school: "SPCH",
    title: "Career Development in Sound",
    subject: "SAI",
    number: "580-0",
  },
  {
    course_id: "016508",
    unique_id: "42097",
    school: "SESP",
    title: "Summer Internship",
    subject: "SESP",
    number: "114-0",
  },
  {
    course_id: "021101",
    unique_id: "42098",
    school: "SESP",
    title: "Practicum in Human Development - Washington, D.C.",
    subject: "SESP",
    number: "384-0",
  },
  {
    course_id: "021102",
    unique_id: "42099",
    school: "SESP",
    title: "Practicum in Human Development - San Francisco",
    subject: "SESP",
    number: "389-0",
  },
  {
    course_id: "023918",
    unique_id: "42102",
    school: "SESP",
    title: "Experiential Learning: Practicum",
    subject: "SESP",
    number: "392-0",
  },
  {
    course_id: "003306",
    unique_id: "41742",
    school: "WCAS",
    title: "Introduction to Sociology",
    subject: "SOCIOL",
    number: "110-0",
  },
  {
    course_id: "003312",
    unique_id: "41743",
    school: "WCAS",
    title: "Law and Society",
    subject: "SOCIOL",
    number: "206-0",
  },
  {
    course_id: "003316",
    unique_id: "41744",
    school: "WCAS",
    title: "Sociological Analysis",
    subject: "SOCIOL",
    number: "226-0",
  },
  {
    course_id: "019402",
    unique_id: "41746",
    school: "WCAS",
    title: "Sexuality and Society",
    subject: "SOCIOL",
    number: "232-0",
  },
  {
    course_id: "003318",
    unique_id: "41745",
    school: "WCAS",
    title: "Sociology of Organizations",
    subject: "SOCIOL",
    number: "302-0",
  },
  {
    course_id: "003136",
    unique_id: "41418",
    school: "WCAS",
    title: "Elementary Spanish",
    subject: "SPANISH",
    number: "101-1",
  },
  {
    course_id: "003137",
    unique_id: "41419",
    school: "WCAS",
    title: "Elementary Spanish",
    subject: "SPANISH",
    number: "101-2",
  },
  {
    course_id: "003138",
    unique_id: "41420",
    school: "WCAS",
    title: "Elementary Spanish",
    subject: "SPANISH",
    number: "101-3",
  },
  {
    course_id: "003139",
    unique_id: "41421",
    school: "WCAS",
    title: "Intermediate Spanish",
    subject: "SPANISH",
    number: "121-1",
  },
  {
    course_id: "003140",
    unique_id: "41422",
    school: "WCAS",
    title: "Intermediate Spanish",
    subject: "SPANISH",
    number: "121-2",
  },
  {
    course_id: "003141",
    unique_id: "41423",
    school: "WCAS",
    title: "Intermediate Spanish",
    subject: "SPANISH",
    number: "121-3",
  },
  {
    course_id: "015856",
    unique_id: "41426",
    school: "WCAS",
    title: "Language in Context: Contemporary Spain",
    subject: "SPANISH",
    number: "199-0",
  },
  {
    course_id: "003157",
    unique_id: "41424",
    school: "WCAS",
    title: "Conversation on Human Rights: Latin America",
    subject: "SPANISH",
    number: "201-0",
  },
  {
    course_id: "003158",
    unique_id: "41425",
    school: "WCAS",
    title: "Individual and Society through Written Expression",
    subject: "SPANISH",
    number: "203-0",
  },
  {
    course_id: "019257",
    unique_id: "41081",
    school: "UC",
    title: "Continuous Registration",
    subject: "SPS",
    number: "512-0",
  },
  {
    course_id: "003388",
    unique_id: "41777",
    school: "WCAS",
    title: "Introduction to Statistics",
    subject: "STAT",
    number: "202-0",
  },
  {
    course_id: "023705",
    unique_id: "41107",
    school: "UC",
    title: "Introduction to Statistics",
    subject: "STAT",
    number: "202-DL",
  },
  {
    course_id: "017367",
    unique_id: "42138",
    school: "SESP",
    title: "Social Contexts of Education",
    subject: "TEACH_ED",
    number: "302-0",
  },
  {
    course_id: "022279",
    unique_id: "42140",
    school: "SESP",
    title: "Foundations of Learning in a New Language",
    subject: "TEACH_ED",
    number: "310-0",
  },
  {
    course_id: "019649",
    unique_id: "42139",
    school: "SESP",
    title: "Content Area Reading and Writing",
    subject: "TEACH_ED",
    number: "322-0",
  },
  {
    course_id: "000850",
    unique_id: "42136",
    school: "SESP",
    title: "Educating Exceptional Children",
    subject: "TEACH_ED",
    number: "327-0",
  },
  {
    course_id: "020325",
    unique_id: "41749",
    school: "SPCH",
    title: "Musicianship for Actors",
    subject: "THEATRE",
    number: "256-0",
  },
  {
    course_id: "020798",
    unique_id: "41750",
    school: "SPCH",
    title: "Intro to Playwriting",
    subject: "THEATRE",
    number: "281-0",
  },
  {
    course_id: "022935",
    unique_id: "41753",
    school: "SPCH",
    title: "Special Topics in Musical Theatre",
    subject: "THEATRE",
    number: "350-0",
  },
  {
    course_id: "022933",
    unique_id: "42190",
    school: "SPCH",
    title: "Musical Theatre Techniques for Non-Music Theatre Cert",
    subject: "THEATRE",
    number: "353-0",
  },
  {
    course_id: "022900",
    unique_id: "41751",
    school: "SPCH",
    title: "Production Management",
    subject: "THEATRE",
    number: "393-0",
  },
  {
    course_id: "023672",
    unique_id: "41754",
    school: "SPCH",
    title: "Summer Performance",
    subject: "THEATRE",
    number: "475-0",
  },
];

const filter = (searchStr, school, subject, list) => {
  let filtered = filterCoursesByStr(searchStr, list);
  filtered = filterCoursesBySchoolSubject(school, subject, filtered);
  return filtered;
};

// cache previous search and results to speed up searches
let prevStr = "";
let prevResults = [];

export function getCourses({ searchStr: newStr, school, subject }) {
  let list;
  if (newStr.includes(prevStr) && newStr.length - prevStr.length === 1) {
    // optimization
    list = prevResults;
  } else {
    list = courses;
  }
  const results = filter(newStr, school, subject, list);
  prevStr = newStr;
  prevResults = results;
  return results;
}
