const subjects = {
  JOUR: [
    { symbol: "IMC", name: "Integrated Marketing Communications" },
    { symbol: "JOUR", name: "Journalism" },
  ],
  LAW: [
    { symbol: "BUSCOM", name: "Business and Commercial Law" },
    { symbol: "CONPUB", name: "Constitutional and Public Law" },
    { symbol: "CRIM", name: "Criminal Law" },
    { symbol: "INTPROP", name: "Intellectual Property" },
    { symbol: "LAWSTUDY", name: "Law Studies-General or Interdisciplinary" },
    { symbol: "LITARB", name: "Litigation and Arbitration" },
    { symbol: "PPTYTORT", name: "Property and Tort Law" },
    { symbol: "REGLAW", name: "Regulatory Law" },
    { symbol: "TAXLAW", name: "Taxation Law" },
  ],
  MEAS: [
    { symbol: "BMD_ENG", name: "Biomedical Engineering" },
    { symbol: "CHEM_ENG", name: "Chemical Engineering" },
    { symbol: "CIV_ENV", name: "Civil and Environmental Engineering" },
    { symbol: "COMP_ENG", name: "Computer Engineering" },
    { symbol: "COMP_SCI", name: "Computer Science" },
    { symbol: "CRDV", name: "Career Development" },
    { symbol: "DSGN", name: "Segal Design Institute" },
    { symbol: "ELEC_ENG", name: "Electrical Engineering" },
    { symbol: "ENTREP", name: "Entrepreneurship & Innovation" },
    { symbol: "ES_APPM", name: "Engineering Science & Applied Math" },
    { symbol: "GEN_ENG", name: "General Engineering" },
    { symbol: "IEMS", name: "Industrial Engineering & Management Sciences" },
    { symbol: "INF_TECH", name: "Information Technology" },
    { symbol: "ISEN", name: "Initiative for Sustainability & Energy at NU" },
    { symbol: "LDRSHP", name: "Center for Leadership" },
    { symbol: "MAT_SCI", name: "Materials Science & Engineering" },
    { symbol: "MBIOTECH", name: "Masters in Biotechnology Program" },
    { symbol: "MECH_ENG", name: "Mechanical Engineering" },
    { symbol: "MEM", name: "Master of Engineering Management" },
    { symbol: "MSAI", name: "Artificial Intelligence" },
    { symbol: "MSIA", name: "Master of Science in Analytics" },
    { symbol: "PRDV", name: "Personal Development" },
    { symbol: "PROJ_MGT", name: "Project Management" },
    { symbol: "PSED", name: "Predictive Science and Engineering" },
  ],
  SESP: [
    { symbol: "HDC", name: "Human Development in Context" },
    { symbol: "HDSP", name: "Human Development & Social Policy" },
    { symbol: "LOC", name: "Learning & Organizational Change" },
    { symbol: "LRN_SCI", name: "Learning Sciences" },
    { symbol: "MS_ED", name: "MS in Education & Social Policy" },
    {
      symbol: "MS_HE",
      name: "MS in Higher Education Administration and Policy",
    },
    { symbol: "MS_LOC", name: "Learning & Organizational Change" },
    { symbol: "SESP", name: "School of Education & Social Policy Core" },
    { symbol: "SE_POL", name: "Social & Economic Policy" },
    { symbol: "SOC_POL", name: "Social Policy" },
    { symbol: "TEACH_ED", name: "Teacher Education" },
  ],
  SPCH: [
    { symbol: "CMN", name: "Communication Related Courses" },
    { symbol: "COMM_ST", name: "Communication Studies" },
    { symbol: "CSD", name: "Communication Sciences and Disorders" },
    { symbol: "DANCE", name: "Dance" },
    { symbol: "HLTH_COM", name: "Health Communication" },
    { symbol: "MSC", name: "Master of Science in Communication" },
    { symbol: "MSLCE", name: "MS Leadership for Creative Enterprises" },
    { symbol: "MTS", name: "Media, Technology & Society" },
    { symbol: "PERF_ST", name: "Performance Studies" },
    { symbol: "RTVF", name: "Radio/Television/Film" },
    { symbol: "SAI", name: "Sound Arts and Industries" },
    { symbol: "THEATRE", name: "Theatre" },
  ],
  TGS: [
    { symbol: "APP_PHYS", name: "Applied Physics" },
    { symbol: "BIOSTAT", name: "Biostatistics" },
    { symbol: "CHSS", name: "Comparative & Historical Social Science" },
    { symbol: "CIC", name: "CIC Traveling Scholar" },
    { symbol: "CLIN_PSY", name: "Clinical Psychology" },
    { symbol: "CME", name: "Chicago Metropolitan Exchange Program" },
    { symbol: "COUN", name: "Counseling" },
    { symbol: "DATA_SCI", name: "Data Science" },
    { symbol: "DGP", name: "Driskill Graduate Program in Life Sciences" },
    { symbol: "GENET_CN", name: "Genetic Counseling" },
    { symbol: "HBMI", name: "Health and Biomedical Informatics" },
    { symbol: "HQS", name: "Healthcare Quality and Patient  Safety" },
    { symbol: "HSIP", name: "Health Sciences Integrated Program" },
    { symbol: "HSR", name: "Health Services and Outcomes Research" },
    { symbol: "LRN_SCI", name: "Learning Sciences" },
    { symbol: "MENA", name: "Middle East and North African Studies" },
    { symbol: "MHB", name: "Medical Humanities and Bioethics" },
    { symbol: "MSCI", name: "Master of Science in Clinical Investigation" },
    { symbol: "MS_FT", name: "MS in Marital & Family Therapy" },
    { symbol: "NUIN", name: "Neuroscience" },
    { symbol: "PBC", name: "Plant Biology & Conservation" },
    { symbol: "PUB_HLTH", name: "Public Health" },
    { symbol: "QSB", name: "Quantitative and Systems Biology" },
    { symbol: "REPR_SCI", name: "Reproductive Science and Medicine" },
    { symbol: "TGS", name: "TGS General Registrations" },
    { symbol: "THEATRE", name: "Theatre" },
  ],
  WCAS: [
    { symbol: "AFST", name: "African Studies" },
    { symbol: "AF_AM_ST", name: "African American Studies" },
    { symbol: "AMER_ST", name: "American Studies" },
    { symbol: "ANTHRO", name: "Anthropology" },
    { symbol: "ARABIC", name: "Arabic" },
    { symbol: "ART", name: "Art Theory & Practice" },
    { symbol: "ART_HIST", name: "Art History" },
    { symbol: "ASIAN_AM", name: "Asian American Studies" },
    { symbol: "ASIAN_LC", name: "Asian Languages and Cultures" },
    { symbol: "ASTRON", name: "Astronomy" },
    { symbol: "BIOL_SCI", name: "Biological Sciences" },
    { symbol: "BUS_INST", name: "Business Institutions" },
    { symbol: "CFS", name: "Chicago Field Studies" },
    { symbol: "CHEM", name: "Chemistry" },
    { symbol: "CHINESE", name: "Chinese" },
    { symbol: "CLASSICS", name: "Classics - Readings in English" },
    { symbol: "COG_SCI", name: "Cognitive Science" },
    { symbol: "COMP_LIT", name: "Comparative Literary Studies" },
    { symbol: "EARTH", name: "Earth and Planetary Sciences" },
    { symbol: "ECON", name: "Economics" },
    { symbol: "ENGLISH", name: "English" },
    { symbol: "ENVR_POL", name: "Environmental Policy & Culture" },
    { symbol: "ENVR_SCI", name: "Environmental Science" },
    { symbol: "FRENCH", name: "French" },
    { symbol: "GAMS", name: "Global Avant-garde and Modernist Studies" },
    { symbol: "GBL_HLTH", name: "Global Health" },
    { symbol: "GEN_LA", name: "General Liberal Arts" },
    { symbol: "GEOG", name: "Geography" },
    { symbol: "GERMAN", name: "German" },
    { symbol: "GNDR_ST", name: "Gender Studies" },
    { symbol: "GREEK", name: "Greek" },
    { symbol: "HEBREW", name: "Hebrew" },
    { symbol: "HIND_URD", name: "Hindi and Urdu" },
    { symbol: "HISTORY", name: "History" },
    { symbol: "HUM", name: "Humanities" },
    { symbol: "IBIS", name: "Interdisciplinary Biological Sciences Program" },
    { symbol: "INTG_SCI", name: "Integrated Science" },
    { symbol: "INTL_ST", name: "International Studies" },
    { symbol: "ISEN", name: "Initiative for Sustainability & Energy at NU" },
    { symbol: "ITALIAN", name: "Italian" },
    { symbol: "JAPANESE", name: "Japanese" },
    { symbol: "JWSH_ST", name: "Jewish Studies" },
    { symbol: "KOREAN", name: "Korean" },
    { symbol: "LATIN", name: "Latin" },
    { symbol: "LATINO", name: "Latina and Latino Studies" },
    { symbol: "LEGAL_ST", name: "Legal Studies" },
    { symbol: "LING", name: "Linguistics" },
    { symbol: "MATH", name: "Mathematics" },
    { symbol: "MENA", name: "Middle East and North African Studies" },
    { symbol: "MMSS", name: "Math Methods in the Social Sciences" },
    { symbol: "NEUROBIO", name: "Neurobiology & Physiology" },
    { symbol: "NEUROSCI", name: "Neuroscience" },
    { symbol: "PERSIAN", name: "Persian" },
    { symbol: "PHIL", name: "Philosophy" },
    { symbol: "PHYSICS", name: "Physics" },
    { symbol: "POLISH", name: "Polish" },
    { symbol: "POLI_SCI", name: "Political Science" },
    { symbol: "PORT", name: "Portuguese" },
    { symbol: "PSYCH", name: "Psychology" },
    { symbol: "RELIGION", name: "Religious Studies" },
    { symbol: "RUSSIAN", name: "Russian" },
    { symbol: "SLAVIC", name: "Slavic Languages & Literature" },
    { symbol: "SOCIOL", name: "Sociology" },
    { symbol: "SPANISH", name: "Spanish" },
    { symbol: "SPANPORT", name: "Spanish and Portuguese" },
    { symbol: "STAT", name: "Statistics" },
    { symbol: "SWAHILI", name: "Swahili" },
    { symbol: "TRANS", name: "Transportation" },
    { symbol: "TURKISH", name: "Turkish" },
  ],
};

export function getSubject(school) {
  return subjects[school] || [];
}
