const subjects = {
  JOUR: [
    { symbol: "IMC", name: "Integrated Marketing Communications" },
    { symbol: "JOUR", name: "Journalism" },
  ],
  LAW: [
    { symbol: "BUSCOM", name: "Business and Commercial Law" },
    { symbol: "CONPUB", name: "Constitutional and Public Law" },
    { symbol: "CRIM", name: "Criminal Law" },
    { symbol: "INTPROP", name: "Intellectual Property" },
    { symbol: "LAWSTUDY", name: "Law Studies-General or Interdisciplinary" },
    { symbol: "LITARB", name: "Litigation and Arbitration" },
  ],
  MEAS: [
    { symbol: "BMD_ENG", name: "Biomedical Engineering" },
    { symbol: "CHEM_ENG", name: "Chemical Engineering" },
    { symbol: "CIV_ENV", name: "Civil and Environmental Engineering" },
    { symbol: "COMP_ENG", name: "Computer Engineering" },
    { symbol: "COMP_SCI", name: "Computer Science" },
    { symbol: "CRDV", name: "Career Development" },
    { symbol: "DSGN", name: "Segal Design Institute" },
    { symbol: "ELEC_ENG", name: "Electrical Engineering" },
    { symbol: "ES_APPM", name: "Engineering Science & Applied Math" },
    { symbol: "GEN_ENG", name: "General Engineering" },
    { symbol: "IEMS", name: "Industrial Engineering & Management Sciences" },
    { symbol: "MAT_SCI", name: "Materials Science & Engineering" },
    { symbol: "MBIOTECH", name: "Masters in Biotechnology Program" },
    { symbol: "MECH_ENG", name: "Mechanical Engineering" },
  ],
  SESP: [
    { symbol: "MS_ED", name: "MS in Education & Social Policy" },
    {
      symbol: "MS_HE",
      name: "MS in Higher Education Administration and Policy",
    },
    { symbol: "MS_LOC", name: "Learning & Organizational Change" },
    { symbol: "SESP", name: "School of Education & Social Policy Core" },
    { symbol: "TEACH_ED", name: "Teacher Education" },
  ],
  SPCH: [
    { symbol: "CMN", name: "Communication Related Courses" },
    { symbol: "COMM_ST", name: "Communication Studies" },
    { symbol: "CSD", name: "Communication Sciences and Disorders" },
    { symbol: "HLTH_COM", name: "Health Communication" },
    { symbol: "MSC", name: "Master of Science in Communication" },
    { symbol: "MSLCE", name: "MS Leadership for Creative Enterprises" },
    { symbol: "MTS", name: "Media, Technology & Society" },
    { symbol: "PERF_ST", name: "Performance Studies" },
    { symbol: "RTVF", name: "Radio/Television/Film" },
    { symbol: "SAI", name: "Sound Arts and Industries" },
    { symbol: "THEATRE", name: "Theatre" },
  ],
  UC: [
    { symbol: "ACCOUNT", name: "Accounting" },
    { symbol: "BIOL_SCI", name: "Biological Sciences" },
    { symbol: "BUS_ANLY", name: "Business Analytics" },
    { symbol: "CIS", name: "Computer Information Systems" },
    {
      symbol: "CLIN_RES",
      name: "Clinical Research & Regulatory Administration",
    },
    { symbol: "CODING", name: "Coding Boot Camp" },
    { symbol: "COMM_ST", name: "Communication Studies" },
    { symbol: "CSD", name: "Communication Sciences and Disorders" },
    { symbol: "CYBER_BC", name: "Cybersecurity Boot Camp" },
    { symbol: "DATA_BC", name: "Data Science Boot Camp" },
    { symbol: "DIV_MED", name: "Divorce Mediation Training Program" },
    { symbol: "ENGLISH", name: "English" },
    { symbol: "FINANCE", name: "Finance" },
    { symbol: "FNTEC_BC", name: "FinTech Boot Camp" },
    { symbol: "FN_EXTND", name: "CFP Extended" },
    { symbol: "HC_COM", name: "Healthcare Compliance" },
    { symbol: "IPLS", name: "Liberal Studies" },
    { symbol: "JRN_WRIT", name: "Journalistic Writing" },
    { symbol: "LEAD_ART", name: "Art of  Leadership Development" },
    { symbol: "LIT", name: "Literature" },
    { symbol: "MCW", name: "Master of Creative Writing" },
    { symbol: "MED_SKIL", name: "Mediation Skills Training Program" },
    { symbol: "MHI", name: "MS in Health Informatics" },
    { symbol: "MKTG", name: "Marketing" },
    { symbol: "MPPA", name: "Master of Public Policy & Administration" },
    { symbol: "MSA", name: "Master of Arts in Sports Administration" },
    { symbol: "MSDS", name: "Master of Data Science" },
    { symbol: "MSGH", name: "Master of Science Global Health" },
    { symbol: "MSHA", name: "Master of Science in Health Analytics" },
    { symbol: "MSRC", name: "Master of Regulatory Compliance" },
    { symbol: "MS_DSP", name: "Master of Data Science Programme" },
    {
      symbol: "MS_IDS",
      name: "Master of Science Information Design & Strategy",
    },
    { symbol: "MUSEUM", name: "Museum Studies" },
    { symbol: "ORG_BEH", name: "Organizational Behavior" },
    { symbol: "PHIL_NP", name: "Philanthropy and Nonprofit Fundraising" },
    { symbol: "PROJ_PMI", name: "Project Management" },
    { symbol: "PRO_HLTH", name: "Professional Health" },
    { symbol: "PSYCH", name: "Psychology" },
    { symbol: "QARS", name: "Quality Assurance & Regulatory Science" },
    { symbol: "SPS", name: "School of Professional Studies" },
    { symbol: "STAT", name: "Statistics" },
  ],
  WCAS: [
    { symbol: "AFST", name: "African Studies" },
    { symbol: "AF_AM_ST", name: "African American Studies" },
    { symbol: "ANTHRO", name: "Anthropology" },
    { symbol: "ARABIC", name: "Arabic" },
    { symbol: "ART", name: "Art Theory & Practice" },
    { symbol: "ART_HIST", name: "Art History" },
    { symbol: "ASTRON", name: "Astronomy" },
    { symbol: "BIOL_SCI", name: "Biological Sciences" },
    { symbol: "CFS", name: "Chicago Field Studies" },
    { symbol: "CHEM", name: "Chemistry" },
    { symbol: "CHINESE", name: "Chinese" },
    { symbol: "COMP_LIT", name: "Comparative Literary Studies" },
    { symbol: "ECON", name: "Economics" },
    { symbol: "ENGLISH", name: "English" },
    { symbol: "ENVR_POL", name: "Environmental Policy & Culture" },
    { symbol: "ENVR_SCI", name: "Environmental Science" },
    { symbol: "FRENCH", name: "French" },
    { symbol: "GBL_HLTH", name: "Global Health" },
    { symbol: "GERMAN", name: "German" },
    { symbol: "GNDR_ST", name: "Gender Studies" },
    { symbol: "HISTORY", name: "History" },
    { symbol: "IBIS", name: "Interdisciplinary Biological Sciences Program" },
    { symbol: "INTL_ST", name: "International Studies" },
    { symbol: "ITALIAN", name: "Italian" },
    { symbol: "KOREAN", name: "Korean" },
    { symbol: "LATINO", name: "Latina and Latino Studies" },
    { symbol: "LEGAL_ST", name: "Legal Studies" },
    { symbol: "LING", name: "Linguistics" },
    { symbol: "MATH", name: "Mathematics" },
    { symbol: "PHIL", name: "Philosophy" },
    { symbol: "PHYSICS", name: "Physics" },
    { symbol: "POLI_SCI", name: "Political Science" },
    { symbol: "PORT", name: "Portuguese" },
    { symbol: "PSYCH", name: "Psychology" },
    { symbol: "RELIGION", name: "Religious Studies" },
    { symbol: "SOCIOL", name: "Sociology" },
    { symbol: "SPANISH", name: "Spanish" },
    { symbol: "SPANPORT", name: "Spanish and Portuguese" },
    { symbol: "STAT", name: "Statistics" },
  ],
};

export function getSubject(school) {
  return subjects[school] || [];
}
